slogo_team06: backEnd.turtle.Turtle Class Reference
backEnd.turtle.Turtle Class Reference
Public Member Functions
Turtle (String id, double canvasWidth, double canvasHeight)
void moveTurtle (double distance)
void turnTurtle (double change)
Double getMyX ()
Double getMyY ()
Double goHome ()
void clearMyLines ()
void setStamp ()
void clearStamp ()
double goTo (double x, double y)
void togglePen (double d)
void toggleVisibility (double d)
TurtlePoint getPosition ()
void setPosition (Point2D newPosition)
double getOrientation ()
void setOrientation (Double newOrientation)
double turnTowards (double x, double y)
boolean isPenDown ()
boolean isVisible ()
TurtleProperties getTurtleProperties ()
String getId ()
Pen getPen ()
void setShapeIndex (double index)
DoubleProperty getShapeIndex ()
void setIsActive (boolean alive)
BooleanProperty getIsActive ()
Static Public Attributes
static final boolean INITIAL_VISIBILITY = true
static final double INITIAL_ORIENTATION = 0
static final boolean INITIAL_PEN = true
static final boolean INITIAL_CLEAR = false
static final boolean INITIAL_ACTIVITY = true
static final double INITIAL_STAMP_COUNT = 0
static final int INITIAL_SHAPE_INDEX = 0
static final int DEGREES_IN_A_CIRCLE = 360
Protected Member Functions
void toroidalMovement (double deltaX, double deltaY)
Private Member Functions
void movementHelper (double direction, int penState)
Private Attributes
BooleanProperty myPenDown
TurtlePoint myPosition
DoubleProperty myOrientation
double myCanvasWidth
double myCanvasHeight
BooleanProperty myClearLines
String myId
DoubleProperty myShapeIndex
DoubleProperty myStampCount
BooleanProperty myActivity
Point2D myHome
BooleanProperty myVisibility
Pen myPen
Detailed Description
Hold all information and behaviors for the turtle in SLogo. The turtle is capable of turning and moving, as well as hiding. It hold a pen which it can raise and lower, altering when lines are drawn. It always begins at the origin and can return home.
Author
Ethan Chang
Eli Lichtenberg
Definition at line 20 of file Turtle.java.
Constructor & Destructor Documentation
backEnd.turtle.Turtle.Turtle (String id, double canvasWidth, double canvasHeight)
Constructor, takes an id name, as well as the dimensions of the canvas the turtle will appear on.
Parameters
id the turtle's name
canvasWidth width of the canvas
canvasHeight height of the canvas
Definition at line 55 of file Turtle.java.
References backEnd.turtle.TurtlePoint.getX(), and backEnd.turtle.TurtlePoint.getY().
Member Function Documentation
void backEnd.turtle.Turtle.clearMyLines ()
Clears the lines the turtle has drawn
Definition at line 137 of file Turtle.java.
void backEnd.turtle.Turtle.clearStamp ()
Remomves all stamps the turtle has drawn.
Definition at line 153 of file Turtle.java.
String backEnd.turtle.Turtle.getId ()
Get the turtle's name
Returns
turtle's name
Definition at line 313 of file Turtle.java.
References backEnd.turtle.Turtle.myId.
BooleanProperty backEnd.turtle.Turtle.getIsActive ()
Definition at line 345 of file Turtle.java.
References backEnd.turtle.Turtle.myActivity.
Double backEnd.turtle.Turtle.getMyX ()
Retrieves the turtle's X value
Returns
turtle's x-value
Definition at line 112 of file Turtle.java.
References backEnd.turtle.TurtlePoint.getX().
Double backEnd.turtle.Turtle.getMyY ()
Retrieves the turtle's Y value
Returns
turtle's y-value
Definition at line 120 of file Turtle.java.
References backEnd.turtle.TurtlePoint.getY().
double backEnd.turtle.Turtle.getOrientation ()
Get turtle's orientation
Returns
the turtle's orientation
Definition at line 217 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.movementHelper(), and backEnd.turtle.Turtle.turnTurtle().
Pen backEnd.turtle.Turtle.getPen ()
Get the turtle's pen
Returns
Definition at line 321 of file Turtle.java.
References backEnd.turtle.Turtle.myPen.
TurtlePoint backEnd.turtle.Turtle.getPosition ()
return the turtle's current position
Returns
Definition at line 201 of file Turtle.java.
References backEnd.turtle.Turtle.myPosition.
DoubleProperty backEnd.turtle.Turtle.getShapeIndex ()
Return the index the turtle is using as an image
Returns
index used
Definition at line 337 of file Turtle.java.
References backEnd.turtle.Turtle.myShapeIndex.
TurtleProperties backEnd.turtle.Turtle.getTurtleProperties ()
Packages the properties needed in the front end to track the turtle
Returns
TurtleProperties containing the necessary properties
Definition at line 301 of file Turtle.java.
Double backEnd.turtle.Turtle.goHome ()
Returns the turtle home (0,0)
Returns
distance travelled to go ome
Definition at line 128 of file Turtle.java.
References backEnd.turtle.TurtlePoint.distance(), and backEnd.turtle.TurtlePoint.set().
double backEnd.turtle.Turtle.goTo (double x, double y)
Goes to a specific location on the canvas
Parameters
x x-coordinate of the location
y y-coordinate of the location
Returns
Definition at line 163 of file Turtle.java.
References backEnd.turtle.TurtlePoint.distance(), and backEnd.turtle.TurtlePoint.set().
boolean backEnd.turtle.Turtle.isPenDown ()
Checks if the pen is currently down
Returns
pen's current state
Definition at line 285 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.moveTurtle().
boolean backEnd.turtle.Turtle.isVisible ()
Check if the turtle is visible
Returns
the turtle's visibility
Definition at line 293 of file Turtle.java.
void backEnd.turtle.Turtle.movementHelper (double direction, int penState) private
Calculates the change in x and y for each incremental move.
Parameters
direction whether going forward or backwards
penState whether the pen is up or down
Definition at line 93 of file Turtle.java.
References backEnd.turtle.Turtle.getOrientation(), backEnd.turtle.Turtle.togglePen(), and backEnd.turtle.Turtle.toroidalMovement().
Referenced by backEnd.turtle.Turtle.moveTurtle().
void backEnd.turtle.Turtle.moveTurtle (double distance)
Moves the turtle unit by unit.
Parameters
distance how far the turtle needs to move.
Definition at line 75 of file Turtle.java.
References backEnd.turtle.Turtle.isPenDown(), and backEnd.turtle.Turtle.movementHelper().
void backEnd.turtle.Turtle.setIsActive (boolean alive)
Definition at line 341 of file Turtle.java.
void backEnd.turtle.Turtle.setOrientation (Double newOrientation)
Set the turtle's orientation
Parameters
newOrientation new orientation
Definition at line 225 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.turnTowards(), and backEnd.turtle.Turtle.turnTurtle().
void backEnd.turtle.Turtle.setPosition (Point2D newPosition)
Sets the position for the turtle
Parameters
newPosition new position on canvs
Definition at line 209 of file Turtle.java.
References backEnd.turtle.TurtlePoint.set().
Referenced by backEnd.turtle.Turtle.toroidalMovement().
void backEnd.turtle.Turtle.setShapeIndex (double index)
Set the index of the shape the turtle will be using
Parameters
index index to be used
Definition at line 329 of file Turtle.java.
void backEnd.turtle.Turtle.setStamp ()
Sets a stamp of the turtle on the canvas
Definition at line 146 of file Turtle.java.
void backEnd.turtle.Turtle.togglePen (double d)
Toggles if the pen is up or down. If the pen is down the turtle can draw. If it isn't, it cannot.
Parameters
d
Definition at line 175 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.movementHelper(), and backEnd.turtle.Turtle.toroidalMovement().
void backEnd.turtle.Turtle.toggleVisibility (double d)
Changes if the turtle is visible on the canvas
Parameters
d whether turtle should be visible
Definition at line 188 of file Turtle.java.
void backEnd.turtle.Turtle.toroidalMovement (double deltaX, double deltaY) protected
Deals with edge cases when moving your turtle. If you go over the top you'll continue from the bottom and if you go pass the left bounds, you'll come out from the right
Parameters
deltaX Change in the turtle's x value
deltaY Change in the turtle's y value
Definition at line 237 of file Turtle.java.
References backEnd.turtle.TurtlePoint.getX(), backEnd.turtle.TurtlePoint.getY(), backEnd.turtle.Turtle.myCanvasHeight, backEnd.turtle.Turtle.myCanvasWidth, backEnd.turtle.Turtle.setPosition(), and backEnd.turtle.Turtle.togglePen().
Referenced by backEnd.turtle.Turtle.movementHelper().
double backEnd.turtle.Turtle.turnTowards (double x, double y)
turn towards a specific point on the canvas
Parameters
x x-coordinate of point
y y-coordinate of point
Returns
degrees turned to face the point
Definition at line 267 of file Turtle.java.
References backEnd.turtle.TurtlePoint.getX(), backEnd.turtle.TurtlePoint.getY(), and backEnd.turtle.Turtle.setOrientation().
void backEnd.turtle.Turtle.turnTurtle (double change)
Rotates the turtle's orientation by chang
Parameters
change factor the orientation changes
Definition at line 104 of file Turtle.java.
References backEnd.turtle.Turtle.getOrientation(), and backEnd.turtle.Turtle.setOrientation().
Member Data Documentation
final int backEnd.turtle.Turtle.DEGREES_IN_A_CIRCLE = 360 static
Definition at line 30 of file Turtle.java.
final boolean backEnd.turtle.Turtle.INITIAL_ACTIVITY = true static
Definition at line 27 of file Turtle.java.
final boolean backEnd.turtle.Turtle.INITIAL_CLEAR = false static
Definition at line 26 of file Turtle.java.
final double backEnd.turtle.Turtle.INITIAL_ORIENTATION = 0 static
Definition at line 24 of file Turtle.java.
final boolean backEnd.turtle.Turtle.INITIAL_PEN = true static
Definition at line 25 of file Turtle.java.
final int backEnd.turtle.Turtle.INITIAL_SHAPE_INDEX = 0 static
Definition at line 29 of file Turtle.java.
final double backEnd.turtle.Turtle.INITIAL_STAMP_COUNT = 0 static
Definition at line 28 of file Turtle.java.
final boolean backEnd.turtle.Turtle.INITIAL_VISIBILITY = true static
Definition at line 23 of file Turtle.java.
BooleanProperty backEnd.turtle.Turtle.myActivity private
Definition at line 40 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.getIsActive().
double backEnd.turtle.Turtle.myCanvasHeight private
Definition at line 35 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.toroidalMovement().
double backEnd.turtle.Turtle.myCanvasWidth private
Definition at line 34 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.toroidalMovement().
BooleanProperty backEnd.turtle.Turtle.myClearLines private
Definition at line 36 of file Turtle.java.
Point2D backEnd.turtle.Turtle.myHome private
Definition at line 42 of file Turtle.java.
String backEnd.turtle.Turtle.myId private
Definition at line 37 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.getId().
DoubleProperty backEnd.turtle.Turtle.myOrientation private
Definition at line 33 of file Turtle.java.
Pen backEnd.turtle.Turtle.myPen private
Definition at line 45 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.getPen().
BooleanProperty backEnd.turtle.Turtle.myPenDown private
Definition at line 31 of file Turtle.java.
TurtlePoint backEnd.turtle.Turtle.myPosition private
Definition at line 32 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.getPosition().
DoubleProperty backEnd.turtle.Turtle.myShapeIndex private
Definition at line 38 of file Turtle.java.
Referenced by backEnd.turtle.Turtle.getShapeIndex().
DoubleProperty backEnd.turtle.Turtle.myStampCount private
Definition at line 39 of file Turtle.java.
BooleanProperty backEnd.turtle.Turtle.myVisibility private
Definition at line 44 of file Turtle.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/turtle/Turtle.java