slogo_team06: main.MasterMenuBar Class Reference
main.MasterMenuBar Class Reference
Public Member Functions
MasterMenuBar (MasterWindow master)
Package Attributes
MasterWindow myMaster
Private Member Functions
Menu buildFileMenu ()
Menu buildEditMenu ()
Menu buildLanguageChooserMenuItem ()
void setLanguage (String s)
MenuItem buildNewWorkspaceMenuItem ()
MenuItem buildSavePreferencesMenuItem ()
MenuItem buildLoadPreferencesMenuItem ()
void saveWorkspacePreferences ()
void loadWorkspacePreferences ()
Detailed Description
Definition at line 13 of file MasterMenuBar.java.
Constructor & Destructor Documentation
main.MasterMenuBar.MasterMenuBar (MasterWindow master)
Definition at line 15 of file MasterMenuBar.java.
References main.MasterMenuBar.buildEditMenu(), and main.MasterMenuBar.buildFileMenu().
Member Function Documentation
Menu main.MasterMenuBar.buildEditMenu () private
Definition at line 27 of file MasterMenuBar.java.
References main.MasterMenuBar.buildLanguageChooserMenuItem().
Referenced by main.MasterMenuBar.MasterMenuBar().
Menu main.MasterMenuBar.buildFileMenu () private
Definition at line 22 of file MasterMenuBar.java.
References main.MasterMenuBar.buildLoadPreferencesMenuItem(), main.MasterMenuBar.buildNewWorkspaceMenuItem(), and main.MasterMenuBar.buildSavePreferencesMenuItem().
Referenced by main.MasterMenuBar.MasterMenuBar().
Menu main.MasterMenuBar.buildLanguageChooserMenuItem () private
Definition at line 32 of file MasterMenuBar.java.
References main.ResourceFinder.getPossibleLanguages(), and main.MasterMenuBar.setLanguage().
Referenced by main.MasterMenuBar.buildEditMenu().
MenuItem main.MasterMenuBar.buildLoadPreferencesMenuItem () private
Definition at line 59 of file MasterMenuBar.java.
References main.MasterMenuBar.loadWorkspacePreferences().
Referenced by main.MasterMenuBar.buildFileMenu().
MenuItem main.MasterMenuBar.buildNewWorkspaceMenuItem () private
Definition at line 49 of file MasterMenuBar.java.
References main.MasterWindow.buildWorkspace().
Referenced by main.MasterMenuBar.buildFileMenu().
MenuItem main.MasterMenuBar.buildSavePreferencesMenuItem () private
Definition at line 54 of file MasterMenuBar.java.
References main.MasterMenuBar.saveWorkspacePreferences().
Referenced by main.MasterMenuBar.buildFileMenu().
void main.MasterMenuBar.loadWorkspacePreferences () private
Definition at line 76 of file MasterMenuBar.java.
References main.MasterWindow.loadWorkspacePreferences().
Referenced by main.MasterMenuBar.buildLoadPreferencesMenuItem().
void main.MasterMenuBar.saveWorkspacePreferences () private
Definition at line 64 of file MasterMenuBar.java.
References main.MasterWindow.saveWorkspacePreferences().
Referenced by main.MasterMenuBar.buildSavePreferencesMenuItem().
void main.MasterMenuBar.setLanguage (String s) private
Definition at line 46 of file MasterMenuBar.java.
References main.ResourceFinder.setLanguage().
Referenced by main.MasterMenuBar.buildLanguageChooserMenuItem().
Member Data Documentation
MasterWindow main.MasterMenuBar.myMaster package
Definition at line 14 of file MasterMenuBar.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/main/MasterMenuBar.java