slogo_team06: main.ResourceFinder Class Reference
main.ResourceFinder Class Reference
Public Member Functions
ResourceFinder ()
ResourceFinder (String language)
Static Public Member Functions
static ResourceBundle getMyLanguageResources ()
static ResourceBundle getMyCommandResources ()
static void setLanguage (String language)
static List< String > getPossibleLanguages ()
Static Private Member Functions
static void setMyLanguageResources (String language)
Static Private Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
static final String DEFAULT_LANGUAGE = "English"
static final ResourceBundle MY_COMMAND_RESOURCES
static final ResourceBundle MY_POSSIBLE_LANGUAGES_RESOURCES
static ResourceBundle myLanguageResources
Detailed Description
Used to get the ResourceBundles for the language and the command list. Called by MasterWindow to set up and change languages, and by the CommandFactory and others to get the names of the commands and more
Author
brianbolze
Definition at line 16 of file ResourceFinder.java.
Constructor & Destructor Documentation
main.ResourceFinder.ResourceFinder ()
Definition at line 27 of file ResourceFinder.java.
References main.ResourceFinder.DEFAULT_LANGUAGE.
main.ResourceFinder.ResourceFinder (String language)
Definition at line 31 of file ResourceFinder.java.
References main.ResourceFinder.setMyLanguageResources().
Member Function Documentation
static ResourceBundle main.ResourceFinder.getMyCommandResources () static
Definition at line 39 of file ResourceFinder.java.
References main.ResourceFinder.MY_COMMAND_RESOURCES.
static ResourceBundle main.ResourceFinder.getMyLanguageResources () static
Definition at line 35 of file ResourceFinder.java.
References main.ResourceFinder.myLanguageResources.
Referenced by commands.CommandFactory.checkLanguage(), titlePanes.CommandTitlePane.CommandTitlePane(), and backEnd.Controller.move10().
static List<String> main.ResourceFinder.getPossibleLanguages () static
Definition at line 47 of file ResourceFinder.java.
Referenced by main.MasterMenuBar.buildLanguageChooserMenuItem(), and tests.LanguageTester.main().
static void main.ResourceFinder.setLanguage (String language) static
Definition at line 43 of file ResourceFinder.java.
References main.ResourceFinder.setMyLanguageResources().
Referenced by main.MasterMenuBar.setLanguage().
static void main.ResourceFinder.setMyLanguageResources (String language) static private
Definition at line 58 of file ResourceFinder.java.
Referenced by main.ResourceFinder.ResourceFinder(), and main.ResourceFinder.setLanguage().
Member Data Documentation
final String main.ResourceFinder.DEFAULT_LANGUAGE = "English" static private
Definition at line 19 of file ResourceFinder.java.
Referenced by main.ResourceFinder.ResourceFinder().
final String main.ResourceFinder.DEFAULT_RESOURCE_PACKAGE = "resources/" static private
Definition at line 18 of file ResourceFinder.java.
final ResourceBundle main.ResourceFinder.MY_COMMAND_RESOURCES static private
Initial value:
= ResourceBundle
            .getBundle("resources/Commands")
Definition at line 20 of file ResourceFinder.java.
Referenced by main.ResourceFinder.getMyCommandResources().
final ResourceBundle main.ResourceFinder.MY_POSSIBLE_LANGUAGES_RESOURCES static private
Initial value:
= ResourceBundle
            .getBundle("resources/languages/Languages")
Definition at line 22 of file ResourceFinder.java.
ResourceBundle main.ResourceFinder.myLanguageResources static private
Definition at line 25 of file ResourceFinder.java.
Referenced by main.ResourceFinder.getMyLanguageResources().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/main/ResourceFinder.java