slogo_team06: frontEnd.View Class Reference
frontEnd.View Class Reference
Public Member Functions
View (double width, double height, String language)
void addControllerAndSetupGui (Controller controller)
void printException (Exception e)
double getCanvasWidth ()
double getCanvasHeight ()
void update (Observable o, Object arg)
void addToHistory (String script)
void addTextToScript (String command)
void changeBackgroundColor (Color c)
void changePenColor (Color c)
void changeTurtleImage (File f)
void toggleGridLines ()
void bindToModelProperties (DoubleProperty backgroundIndex, StringProperty palette)
void updateVariables ()
String getBackgroundColor ()
Private Member Functions
void setupGui ()
Node buildCanvas ()
Node buildSidePanel ()
Node buildScriptPanel ()
Private Attributes
String myLanguage
Controller myController
TurtleCanvas myCanvas
double myWidth
double myHeight
ParameterPanel mySidePanel
ScriptPanel myScriptPanel
Static Private Attributes
static final double GUI_CONSTANT = .75
static final double PADDING = 20
Detailed Description
View for SLogo. Holds a canvas for the graphical representations of turtles and other GUI elements.
Author
Brian Bolze
Ethan Chang
Eli Lichtenberg
Anna Miyajima
Definition at line 28 of file View.java.
Constructor & Destructor Documentation
frontEnd.View.View (double width, double height, String language)
Constructor for view. Sets the language, height, and width of the GUI.
Parameters
width Width of GUI
height Height of GUI
language Langugage in which commands will be read
Definition at line 49 of file View.java.
Member Function Documentation
void frontEnd.View.addControllerAndSetupGui (Controller controller)
Called by Controller constructor
Definition at line 61 of file View.java.
References frontEnd.View.myController, and frontEnd.View.setupGui().
Referenced by backEnd.Controller.Controller().
void frontEnd.View.addTextToScript (String command)
Adds text to the view's script panel.
Parameters
command Command to add to script panel
Definition at line 118 of file View.java.
References panels.ScriptPanel.addTextToScript(), and frontEnd.View.myScriptPanel.
Referenced by backEnd.Controller.addTextToScript().
void frontEnd.View.addToHistory (String script)
Adds the most recently run script to the view's log of past commands.
Parameters
script Most recently run script
Definition at line 110 of file View.java.
References panels.ParameterPanel.addToHistory(), and frontEnd.View.mySidePanel.
Referenced by backEnd.Controller.runScript().
void frontEnd.View.bindToModelProperties (DoubleProperty backgroundIndex, StringProperty palette)
Binds properties between model and view needed to properly display view.
Parameters
backgroundIndex Number representing background color from list of colors
palette Wrapped String representing user inputted color
Definition at line 196 of file View.java.
References frontEnd.TurtleCanvas.bindToModelProperties(), and frontEnd.View.myCanvas.
Referenced by backEnd.Controller.Controller().
Node frontEnd.View.buildCanvas () private
Definition at line 133 of file View.java.
References frontEnd.View.myCanvas, frontEnd.View.myHeight, frontEnd.View.myWidth, and frontEnd.View.printException().
Referenced by frontEnd.View.setupGui().
Node frontEnd.View.buildScriptPanel () private
Definition at line 155 of file View.java.
References frontEnd.View.myController, frontEnd.View.myHeight, frontEnd.View.myScriptPanel, and frontEnd.View.myWidth.
Referenced by frontEnd.View.setupGui().
Node frontEnd.View.buildSidePanel () private
Definition at line 144 of file View.java.
References frontEnd.View.myController, frontEnd.View.myHeight, frontEnd.View.mySidePanel, frontEnd.View.myWidth, and frontEnd.View.printException().
Referenced by frontEnd.View.setupGui().
void frontEnd.View.changeBackgroundColor (Color c)
Changes background color of canvas.
Parameters
c Color to change background of canvas
Definition at line 164 of file View.java.
References frontEnd.TurtleCanvas.changeBackgroundColor(), and frontEnd.View.myCanvas.
Referenced by backEnd.Controller.changeBackgroundColor(), and frontEnd.Workspace.loadDisplayProperties().
void frontEnd.View.changePenColor (Color c)
Changes color of pen.
Parameters
c Color by which to change pen
Definition at line 172 of file View.java.
References frontEnd.TurtleCanvas.changePenColor(), and frontEnd.View.myCanvas.
Referenced by backEnd.Controller.changePenColor().
void frontEnd.View.changeTurtleImage (File f)
Changes image of turtle on canvas.
Parameters
f File holding image of turtle
Definition at line 180 of file View.java.
References frontEnd.TurtleCanvas.changeTurtleImage(), and frontEnd.View.myCanvas.
Referenced by backEnd.Controller.changeTurtleImage().
String frontEnd.View.getBackgroundColor ()
Returns background color of canvas represented as String.
Returns
Background color of canvas
Definition at line 216 of file View.java.
References frontEnd.TurtleCanvas.getBackgroundColor(), and frontEnd.View.myCanvas.
Referenced by frontEnd.Workspace.saveDisplayProperties().
double frontEnd.View.getCanvasHeight ()
Returns height of the view's canvas.
Returns
Height of canvas
Definition at line 86 of file View.java.
References frontEnd.TurtleCanvas.getBoundingHeight(), and frontEnd.View.myCanvas.
Referenced by backEnd.Model.setupTurtleManager().
double frontEnd.View.getCanvasWidth ()
Returns width of the view's canvas.
Returns
Width of canvas
Definition at line 78 of file View.java.
References frontEnd.TurtleCanvas.getBoundingWidth(), and frontEnd.View.myCanvas.
Referenced by backEnd.Model.setupTurtleManager().
void frontEnd.View.printException (Exception e)
Prints exception to GUI.
Parameters
e Exception
Definition at line 70 of file View.java.
References frontEnd.View.myScriptPanel, and panels.ScriptPanel.printException().
Referenced by frontEnd.View.buildCanvas(), frontEnd.View.buildSidePanel(), backEnd.Controller.runScript(), frontEnd.View.update(), and frontEnd.View.updateVariables().
void frontEnd.View.setupGui () private
Definition at line 123 of file View.java.
References frontEnd.View.buildCanvas(), frontEnd.View.buildScriptPanel(), frontEnd.View.buildSidePanel(), frontEnd.View.myHeight, and frontEnd.View.myWidth.
Referenced by frontEnd.View.addControllerAndSetupGui().
void frontEnd.View.toggleGridLines ()
Turns on grid lines if previously off, turns off if previously on.
Definition at line 187 of file View.java.
References frontEnd.View.myCanvas, and frontEnd.TurtleCanvas.toggleGridLines().
Referenced by backEnd.Controller.toggleGridLines().
void frontEnd.View.update (Observable o, Object arg)
Update the view whenever (observed) data changes in the model.
Parameters
arg The data that has been changed
Definition at line 97 of file View.java.
References frontEnd.View.myCanvas, frontEnd.View.printException(), and frontEnd.TurtleCanvas.update().
void frontEnd.View.updateVariables ()
Updates the variables being displayed by the variables pane in the side bar.
Definition at line 203 of file View.java.
References frontEnd.View.mySidePanel, frontEnd.View.printException(), and panels.ParameterPanel.updateVariables().
Referenced by backEnd.Controller.runScript().
Member Data Documentation
final double frontEnd.View.GUI_CONSTANT = .75 static private
Definition at line 30 of file View.java.
TurtleCanvas frontEnd.View.myCanvas private
Definition at line 35 of file View.java.
Referenced by frontEnd.View.bindToModelProperties(), frontEnd.View.buildCanvas(), frontEnd.View.changeBackgroundColor(), frontEnd.View.changePenColor(), frontEnd.View.changeTurtleImage(), frontEnd.View.getBackgroundColor(), frontEnd.View.getCanvasHeight(), frontEnd.View.getCanvasWidth(), frontEnd.View.toggleGridLines(), and frontEnd.View.update().
Controller frontEnd.View.myController private
Definition at line 34 of file View.java.
Referenced by frontEnd.View.addControllerAndSetupGui(), frontEnd.View.buildScriptPanel(), and frontEnd.View.buildSidePanel().
double frontEnd.View.myHeight private
Definition at line 38 of file View.java.
Referenced by frontEnd.View.buildCanvas(), frontEnd.View.buildScriptPanel(), frontEnd.View.buildSidePanel(), and frontEnd.View.setupGui().
String frontEnd.View.myLanguage private
Definition at line 33 of file View.java.
ScriptPanel frontEnd.View.myScriptPanel private
Definition at line 41 of file View.java.
Referenced by frontEnd.View.addTextToScript(), frontEnd.View.buildScriptPanel(), and frontEnd.View.printException().
ParameterPanel frontEnd.View.mySidePanel private
Definition at line 40 of file View.java.
Referenced by frontEnd.View.addToHistory(), frontEnd.View.buildSidePanel(), and frontEnd.View.updateVariables().
double frontEnd.View.myWidth private
Definition at line 37 of file View.java.
Referenced by frontEnd.View.buildCanvas(), frontEnd.View.buildScriptPanel(), frontEnd.View.buildSidePanel(), and frontEnd.View.setupGui().
final double frontEnd.View.PADDING = 20 static private
Definition at line 31 of file View.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/frontEnd/View.java