slogo_team06: frontEnd.TurtleCanvas Class Reference
frontEnd.TurtleCanvas Class Reference
Public Member Functions
TurtleCanvas (double width, double height, double padding) throws IOException
void changeBackgroundColor (Color c)
void changePenColor (Color c)
void changeTurtleImage (File f)
void toggleGridLines ()
double getBoundingWidth ()
double getBoundingHeight ()
String getBackgroundColor ()
Package Functions
void update (Observable o, Object arg) throws IOException
void bindToModelProperties (DoubleProperty backgroundIndex, StringProperty palette)
Private Member Functions
void addTurtle (Turtle turtle) throws IOException
void addBackground ()
void addClipper ()
Rectangle makeRect (double width, double height, double xpos, double ypos)
void addGridLines ()
void addListeners ()
void addPaletteListener ()
void addBackgroundIndexListener ()
Private Attributes
double myBoundingWidth
double myBoundingHeight
double myPadding
DoubleProperty myWidth
DoubleProperty myHeight
Rectangle myBackground
Group myGridLines
TurtleView myTurtleView
DoubleProperty myBackgroundIndex
StringProperty myPalette
Properties myColorProperties
Static Private Attributes
static final double GRID_LINE_WIDTH = .4
static final int NUM_COLS = 20
static final int NUM_ROWS = 20
Detailed Description
Portion of GUI on which graphical representation of turtles move.
Author
Brian Bolze
Ethan Chang
Eli Lichtenberg
Anna Miyajima
Definition at line 33 of file TurtleCanvas.java.
Constructor & Destructor Documentation
frontEnd.TurtleCanvas.TurtleCanvas (double width, double height, double padding) throws IOException
Constructor for TurtleCanvas. Sets width, height, and padding.
Parameters
width Width of canvas GUI element
height Height of canvas GUI element
padding Padding between GUI elements
Exceptions
IOException
Definition at line 58 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.addBackground(), frontEnd.TurtleCanvas.addClipper(), frontEnd.TurtleCanvas.addGridLines(), frontEnd.TurtleCanvas.addListeners(), and frontEnd.TurtleCanvas.myPadding.
Member Function Documentation
void frontEnd.TurtleCanvas.addBackground () private
Definition at line 130 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.makeRect().
Referenced by frontEnd.TurtleCanvas.TurtleCanvas().
void frontEnd.TurtleCanvas.addBackgroundIndexListener () private
Definition at line 215 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.changeBackgroundColor().
Referenced by frontEnd.TurtleCanvas.addListeners().
void frontEnd.TurtleCanvas.addClipper () private
Definition at line 144 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.makeRect().
Referenced by frontEnd.TurtleCanvas.TurtleCanvas().
void frontEnd.TurtleCanvas.addGridLines () private
Definition at line 157 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.NUM_COLS, and frontEnd.TurtleCanvas.NUM_ROWS.
Referenced by frontEnd.TurtleCanvas.TurtleCanvas().
void frontEnd.TurtleCanvas.addListeners () private
Definition at line 196 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.addBackgroundIndexListener(), and frontEnd.TurtleCanvas.addPaletteListener().
Referenced by frontEnd.TurtleCanvas.TurtleCanvas().
void frontEnd.TurtleCanvas.addPaletteListener () private
Definition at line 201 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.addListeners().
void frontEnd.TurtleCanvas.addTurtle (Turtle turtle) throws IOException private
Definition at line 111 of file TurtleCanvas.java.
References frontEnd.TurtleView.getImageView(), frontEnd.TurtleView.getPenLines(), and frontEnd.TurtleView.getStamps().
Referenced by frontEnd.TurtleCanvas.update().
void frontEnd.TurtleCanvas.bindToModelProperties (DoubleProperty backgroundIndex, StringProperty palette) package
Definition at line 190 of file TurtleCanvas.java.
Referenced by frontEnd.View.bindToModelProperties().
void frontEnd.TurtleCanvas.changeBackgroundColor (Color c)
Sets background color of canvas.
Parameters
c Color to make canvas background
Definition at line 83 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.addBackgroundIndexListener(), and frontEnd.View.changeBackgroundColor().
void frontEnd.TurtleCanvas.changePenColor (Color c)
Sets color of turtle's pen.
Parameters
c Color to make pen
Definition at line 91 of file TurtleCanvas.java.
References frontEnd.TurtleView.changePenColor().
Referenced by frontEnd.View.changePenColor().
void frontEnd.TurtleCanvas.changeTurtleImage (File f)
Changes the image used to display a turtle on the canvas.
Parameters
f File holding image
Definition at line 99 of file TurtleCanvas.java.
References frontEnd.TurtleView.setImage().
Referenced by frontEnd.View.changeTurtleImage().
String frontEnd.TurtleCanvas.getBackgroundColor ()
Returns String representing color of background of canvas.
Returns
Background color of canvas as String
Definition at line 232 of file TurtleCanvas.java.
Referenced by frontEnd.View.getBackgroundColor().
double frontEnd.TurtleCanvas.getBoundingHeight ()
Returns the height by which turtles are bounded on the canvas.
Returns
Bounding height of canvas
Definition at line 186 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.myBoundingHeight.
Referenced by frontEnd.View.getCanvasHeight().
double frontEnd.TurtleCanvas.getBoundingWidth ()
Returns the width by which turtles are bounded on the canvas.
Returns
Bounding width of canvas
Definition at line 178 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.myBoundingWidth.
Referenced by frontEnd.View.getCanvasWidth().
Rectangle frontEnd.TurtleCanvas.makeRect (double width, double height, double xpos, double ypos) private
Definition at line 149 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.addBackground(), and frontEnd.TurtleCanvas.addClipper().
void frontEnd.TurtleCanvas.toggleGridLines ()
If grid lines are off, turns on grid lines. If grid lines are on, turns off grid lines.
Definition at line 107 of file TurtleCanvas.java.
Referenced by frontEnd.View.toggleGridLines().
void frontEnd.TurtleCanvas.update (Observable o, Object arg) throws IOException package
Definition at line 122 of file TurtleCanvas.java.
References frontEnd.TurtleCanvas.addTurtle().
Referenced by frontEnd.View.update().
Member Data Documentation
final double frontEnd.TurtleCanvas.GRID_LINE_WIDTH = .4 static private
Definition at line 35 of file TurtleCanvas.java.
Rectangle frontEnd.TurtleCanvas.myBackground private
Definition at line 43 of file TurtleCanvas.java.
DoubleProperty frontEnd.TurtleCanvas.myBackgroundIndex private
Definition at line 46 of file TurtleCanvas.java.
double frontEnd.TurtleCanvas.myBoundingHeight private
Definition at line 39 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.getBoundingHeight().
double frontEnd.TurtleCanvas.myBoundingWidth private
Definition at line 38 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.getBoundingWidth().
Properties frontEnd.TurtleCanvas.myColorProperties private
Definition at line 48 of file TurtleCanvas.java.
Group frontEnd.TurtleCanvas.myGridLines private
Definition at line 44 of file TurtleCanvas.java.
DoubleProperty frontEnd.TurtleCanvas.myHeight private
Definition at line 42 of file TurtleCanvas.java.
double frontEnd.TurtleCanvas.myPadding private
Definition at line 40 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.TurtleCanvas().
StringProperty frontEnd.TurtleCanvas.myPalette private
Definition at line 47 of file TurtleCanvas.java.
TurtleView frontEnd.TurtleCanvas.myTurtleView private
Definition at line 45 of file TurtleCanvas.java.
DoubleProperty frontEnd.TurtleCanvas.myWidth private
Definition at line 41 of file TurtleCanvas.java.
final int frontEnd.TurtleCanvas.NUM_COLS = 20 static private
Definition at line 36 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.addGridLines().
final int frontEnd.TurtleCanvas.NUM_ROWS = 20 static private
Definition at line 37 of file TurtleCanvas.java.
Referenced by frontEnd.TurtleCanvas.addGridLines().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/frontEnd/TurtleCanvas.java