slogo_team06: commands.templates.Command Class Reference
commands.templates.Command Class Reference abstract
Public Member Functions
Command (VariableManager manager)
abstract double execute ()
abstract String toString ()
List< Command > getMyChildren ()
void addChild (Command c)
int getNumChildrenNeeded ()
abstract void initializeCommand (Model model)
Protected Member Functions
void setNumChildren (int numChildren)
void setValue (Double value)
double getValue ()
VariableManager getVariableManager ()
Private Attributes
List< Command > myChildren
int myNumChildren
double myValue
VariableManager myVariableManager
Detailed Description
Superclass for commands. Each sets the number of children that it can hold. i.e. sum can take two children, so its numchildren is set to 0. Commands can then be executed, which returns a double.
Author
Ethan Chang
Anna Miyajima
Definition at line 17 of file Command.java.
Constructor & Destructor Documentation
commands.templates.Command.Command (VariableManager manager)
Definition at line 28 of file Command.java.
Member Function Documentation
void commands.templates.Command.addChild (Command c)
Add child to the command
Parameters
c command to be added
Definition at line 86 of file Command.java.
Referenced by commands.variable_commands.UserDefinedCommand.execute(), backEnd.Parser.makeTree(), and commands.variable_commands.ToCommand.ToCommand().
abstract double commands.templates.Command.execute () abstract
Executes the command by executing each of its children.
Returns
the double result of the command
Referenced by commands.turtle_commands.AskWithCommand.execute(), commands.turtle_commands.TellCommand.execute(), commands.turtle_commands.AskWithCommand.executeTurtleCommand(), and commands.turtle_commands.AskCommand.executeTurtleCommand().
List<Command> commands.templates.Command.getMyChildren ()
Returns the list of children for this command (its arguments)
Returns
Definition at line 47 of file Command.java.
References commands.templates.Command.myChildren.
Referenced by commands.SetPaletteCommand.execute(), commands.onechild.ArcTangentCommand.execute(), commands.onechild.MinusCommand.execute(), commands.onechild.NotCommand.execute(), commands.onechild.CosineCommand.execute(), commands.onechild.SineCommand.execute(), commands.onechild.NaturalLogCommand.execute(), commands.onechild.TangentCommand.execute(), commands.twochildren.AndCommand.execute(), commands.twochildren.DifferenceCommand.execute(), commands.twochildren.EqualCommand.execute(), commands.onechild.RandomCommand.execute(), commands.twochildren.GreaterThanCommand.execute(), commands.twochildren.NotEqualCommand.execute(), commands.twochildren.OrCommand.execute(), commands.twochildren.PowerCommand.execute(), commands.twochildren.ProductCommand.execute(), commands.twochildren.QuotientCommand.execute(), commands.twochildren.SumCommand.execute(), commands.turtle_commands.AskWithCommand.execute(), commands.twochildren.LessThanCommand.execute(), commands.twochildren.RemainderCommand.execute(), commands.turtle_commands.BackCommand.execute(), commands.onechild.SetBackgroundCommand.execute(), commands.variable_commands.RepeatCommand.execute(), commands.variable_commands.MakeCommand.execute(), commands.variable_commands.CommandsList.execute(), commands.variable_commands.IfCommand.execute(), commands.turtle_commands.SetStrokeSize.execute(), commands.variable_commands.ToCommand.execute(), commands.turtle_commands.SetPenColor.execute(), commands.turtle_commands.SetShapeCommand.execute(), commands.turtle_commands.ForwardCommand.execute(), commands.turtle_commands.LeftCommand.execute(), commands.turtle_commands.RightCommand.execute(), commands.variable_commands.IfElseCommand.execute(), commands.turtle_commands.TellCommand.execute(), commands.variable_commands.ForCommand.execute(), commands.variable_commands.DoTimesCommand.execute(), commands.variable_commands.UserDefinedCommand.execute(), commands.variable_commands.UserInputCommand.execute(), commands.turtle_commands.SetHeadingCommand.executeTurtleCommand(), commands.turtle_commands.SetPositionCommand.executeTurtleCommand(), commands.turtle_commands.AskWithCommand.executeTurtleCommand(), commands.turtle_commands.TowardsCommand.executeTurtleCommand(), commands.turtle_commands.AskCommand.executeTurtleCommand(), commands.variable_commands.CommandsList.getChild(), commands.variable_commands.CommandsList.getNumChildren(), commands.variable_commands.UserDefinedCommand.mapVariables(), commands.variable_commands.ToCommand.ToCommand(), commands.onechild.CosineCommand.toString(), commands.onechild.TangentCommand.toString(), commands.onechild.ArcTangentCommand.toString(), commands.onechild.NaturalLogCommand.toString(), commands.onechild.MinusCommand.toString(), commands.onechild.SineCommand.toString(), commands.twochildren.SumCommand.toString(), commands.twochildren.ProductCommand.toString(), commands.twochildren.QuotientCommand.toString(), commands.twochildren.DifferenceCommand.toString(), commands.twochildren.PowerCommand.toString(), commands.twochildren.RemainderCommand.toString(), commands.turtle_commands.BackCommand.toString(), commands.variable_commands.RepeatCommand.toString(), commands.variable_commands.IfCommand.toString(), commands.variable_commands.MakeCommand.toString(), commands.variable_commands.ToCommand.toString(), commands.turtle_commands.ForwardCommand.toString(), commands.variable_commands.IfElseCommand.toString(), commands.turtle_commands.SetHeadingCommand.toString(), commands.turtle_commands.LeftCommand.toString(), commands.turtle_commands.RightCommand.toString(), commands.variable_commands.ForCommand.toString(), commands.variable_commands.DoTimesCommand.toString(), and commands.variable_commands.UserDefinedCommand.UserDefinedCommand().
int commands.templates.Command.getNumChildrenNeeded ()
Get the number of children that can still be added
Returns
children missing
Definition at line 95 of file Command.java.
Referenced by backEnd.Parser.makeTree().
double commands.templates.Command.getValue () protected
Retrieve value returned by the command
Returns
value returned by command
Definition at line 76 of file Command.java.
References commands.templates.Command.myValue.
Referenced by commands.turtle_commands.TurtlesCommand.execute(), commands.turtle_commands.XCorQuery.execute(), commands.onechild.SetBackgroundCommand.execute(), commands.turtle_commands.YCorQuery.execute(), commands.turtle_commands.StampCommand.execute(), commands.turtle_commands.SetHeadingCommand.execute(), commands.turtle_commands.ClearCommand.execute(), commands.turtle_commands.PenDownQuery.execute(), commands.turtle_commands.PenColorCommand.execute(), commands.turtle_commands.IdCommand.execute(), commands.turtle_commands.SetPenColor.execute(), commands.turtle_commands.SetPositionCommand.execute(), commands.turtle_commands.IsShowingQuery.execute(), commands.turtle_commands.SetStrokeSize.execute(), commands.turtle_commands.GetShapeCommand.execute(), commands.turtle_commands.HomeCommand.execute(), commands.turtle_commands.SetShapeCommand.execute(), commands.turtle_commands.HeadingQuery.execute(), commands.turtle_commands.TowardsCommand.execute(), commands.turtle_commands.AskCommand.execute(), commands.turtle_commands.TellCommand.execute(), commands.turtle_commands.SetStrokeSize.executeTurtleCommand(), commands.turtle_commands.SetPenColor.executeTurtleCommand(), commands.turtle_commands.SetShapeCommand.executeTurtleCommand(), commands.turtle_commands.RightCommand.executeTurtleCommand(), commands.turtle_commands.BackCommand.executeTurtleCommand(), commands.turtle_commands.LeftCommand.executeTurtleCommand(), commands.turtle_commands.ForwardCommand.executeTurtleCommand(), commands.turtle_commands.XCorQuery.toString(), commands.turtle_commands.YCorQuery.toString(), commands.turtle_commands.TurtlesCommand.toString(), commands.turtle_commands.PenDownQuery.toString(), commands.turtle_commands.HeadingQuery.toString(), commands.turtle_commands.IsShowingQuery.toString(), commands.turtle_commands.IdCommand.toString(), commands.turtle_commands.SetPositionCommand.toString(), commands.turtle_commands.HomeCommand.toString(), and commands.turtle_commands.TowardsCommand.toString().
VariableManager commands.templates.Command.getVariableManager () protected
Definition at line 107 of file Command.java.
References commands.templates.Command.myVariableManager.
Referenced by commands.variable_commands.ForCommand.execute(), commands.variable_commands.Variable.execute(), commands.variable_commands.DoTimesCommand.execute(), and commands.variable_commands.UserDefinedCommand.UserDefinedCommand().
abstract void commands.templates.Command.initializeCommand (Model model) abstract
Adds anything that the command might need from the model i.e. turtles for turtle commands
Parameters
m
Referenced by commands.CommandFactory.buildCommand().
void commands.templates.Command.setNumChildren (int numChildren) protected
Sets the number of children/arguments the command will take
Parameters
numChildren number of arguments command will take
Definition at line 57 of file Command.java.
Referenced by commands.turtle_commands.AskCommand.AskCommand(), commands.turtle_commands.AskWithCommand.AskWithCommand(), commands.turtle_commands.BackCommand.BackCommand(), commands.turtle_commands.ClearStampCommand.ClearStampCommand(), commands.turtle_commands.ForwardCommand.ForwardCommand(), commands.turtle_commands.GetShapeCommand.GetShapeCommand(), commands.turtle_commands.HeadingQuery.HeadingQuery(), commands.turtle_commands.HideTurtleCommand.HideTurtleCommand(), commands.turtle_commands.HomeCommand.HomeCommand(), commands.turtle_commands.IdCommand.IdCommand(), commands.variable_commands.IfElseCommand.IfElseCommand(), commands.turtle_commands.IsShowingQuery.IsShowingQuery(), commands.turtle_commands.LeftCommand.LeftCommand(), commands.templates.OneChildCommand.OneChildCommand(), commands.turtle_commands.PenColorCommand.PenColorCommand(), commands.turtle_commands.PenDownCommand.PenDownCommand(), commands.turtle_commands.PenDownQuery.PenDownQuery(), commands.turtle_commands.PenUpCommand.PenUpCommand(), commands.turtle_commands.RightCommand.RightCommand(), commands.turtle_commands.SetHeadingCommand.SetHeadingCommand(), commands.SetPaletteCommand.SetPaletteCommand(), commands.turtle_commands.SetPenColor.SetPenColor(), commands.turtle_commands.SetPositionCommand.SetPositionCommand(), commands.turtle_commands.SetShapeCommand.SetShapeCommand(), commands.turtle_commands.SetStrokeSize.SetStrokeSize(), commands.turtle_commands.ShowTurtleCommand.ShowTurtleCommand(), commands.turtle_commands.StampCommand.StampCommand(), commands.turtle_commands.TellCommand.TellCommand(), commands.turtle_commands.TowardsCommand.TowardsCommand(), commands.templates.TwoChildCommand.TwoChildCommand(), commands.variable_commands.UserDefinedCommand.UserDefinedCommand(), commands.variable_commands.UserInputCommand.UserInputCommand(), commands.turtle_commands.XCorQuery.XCorQuery(), and commands.turtle_commands.YCorQuery.YCorQuery().
void commands.templates.Command.setValue (Double value) protected
Stores the value the command returns
Parameters
value value command returns
Definition at line 67 of file Command.java.
Referenced by commands.turtle_commands.XCorQuery.execute(), commands.turtle_commands.BackCommand.execute(), commands.onechild.SetBackgroundCommand.execute(), commands.turtle_commands.YCorQuery.execute(), commands.turtle_commands.SetPenColor.execute(), commands.turtle_commands.IsShowingQuery.execute(), commands.turtle_commands.SetStrokeSize.execute(), commands.turtle_commands.PenDownQuery.execute(), commands.turtle_commands.HeadingQuery.execute(), commands.turtle_commands.SetShapeCommand.execute(), commands.turtle_commands.LeftCommand.execute(), commands.turtle_commands.ForwardCommand.execute(), commands.turtle_commands.RightCommand.execute(), commands.turtle_commands.TellCommand.execute(), commands.turtle_commands.TurtlesCommand.executeTurtleCommand(), commands.turtle_commands.StampCommand.executeTurtleCommand(), commands.turtle_commands.SetHeadingCommand.executeTurtleCommand(), commands.turtle_commands.ClearCommand.executeTurtleCommand(), commands.turtle_commands.PenColorCommand.executeTurtleCommand(), commands.turtle_commands.SetPositionCommand.executeTurtleCommand(), commands.turtle_commands.GetShapeCommand.executeTurtleCommand(), commands.turtle_commands.IdCommand.executeTurtleCommand(), commands.turtle_commands.HomeCommand.executeTurtleCommand(), commands.turtle_commands.AskWithCommand.executeTurtleCommand(), commands.turtle_commands.TowardsCommand.executeTurtleCommand(), and commands.turtle_commands.AskCommand.executeTurtleCommand().
abstract String commands.templates.Command.toString () abstract
Referenced by commands.variable_commands.UserInputCommand.execute(), commands.variable_commands.UserDefinedCommand.mapVariables(), and backEnd.Parser.parseScript().
Member Data Documentation
List<Command> commands.templates.Command.myChildren private
Definition at line 19 of file Command.java.
Referenced by commands.templates.Command.getMyChildren().
int commands.templates.Command.myNumChildren private
Definition at line 20 of file Command.java.
double commands.templates.Command.myValue private
Definition at line 21 of file Command.java.
Referenced by commands.templates.Command.getValue().
VariableManager commands.templates.Command.myVariableManager private
Definition at line 22 of file Command.java.
Referenced by commands.templates.Command.getVariableManager().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/commands/templates/Command.java