slogo_team06: backEnd.turtle.TurtleManager Class Reference
backEnd.turtle.TurtleManager Class Reference
Public Member Functions
TurtleManager (double canvasWidth, double canvasHeight)
void updateActiveTurtleList (List< Double > turtleIds)
void addTemporaryTurtleList (List< Double > turtleIds)
List< Turtle > getTurtleList ()
void updateStoredTurtleLists ()
int getNumberOfTurtles ()
Static Public Attributes
static final String INITIAL_TURTLE = "turtle1"
Private Member Functions
void addNewTurtle (Double turtleId)
List< Turtle > createTurtleList (List< Double > turtleIds)
Private Attributes
Map< Double, Turtle > myTurtles
double myCanvasWidth
double myCanvasHeight
Stack< List< Turtle > > myStoredTurtleLists
List< Turtle > myActiveTurtles
Detailed Description
Turtle manager for slogo. Keeps track of all turtles as well as which ones are active/inactive. These lists are kept on a stack where the bottom-most list is a list of all current active turtles. Once temporary lists are used (ask commands) they can be popped on the stack.
Author
Ethan Chang
Definition at line 20 of file TurtleManager.java.
Constructor & Destructor Documentation
backEnd.turtle.TurtleManager.TurtleManager (double canvasWidth, double canvasHeight)
Constructor for turtle manager. Initializes a map which will map the string names of turtles (their id) with the actual turtle. Also creates the stack which will be used to keep track of temporary and active turtle lists. Does not initially add a turtle because observer must first be attached before a new turtles can be added.
Parameters
canvasWidth the width of the canvas the turtle will be added to
canvasHeight the height of the canvas the turtle will be added to
Definition at line 42 of file TurtleManager.java.
Member Function Documentation
void backEnd.turtle.TurtleManager.addNewTurtle (Double turtleId) private
Creates a new turtle if a with a given id does not already exist.
Parameters
turtleName id of the turtle
Definition at line 57 of file TurtleManager.java.
References backEnd.turtle.TurtleManager.myCanvasHeight, and backEnd.turtle.TurtleManager.myCanvasWidth.
Referenced by backEnd.turtle.TurtleManager.createTurtleList().
void backEnd.turtle.TurtleManager.addTemporaryTurtleList (List< Double > turtleIds)
Creates a list of temporary turtles for the ask command. After the command finishes, these commands should be forgotten, so we add them to the top of the stack.
Parameters
turtleNames
Definition at line 113 of file TurtleManager.java.
References backEnd.turtle.TurtleManager.createTurtleList().
Referenced by commands.turtle_commands.AskCommand.executeTurtleCommand().
List<Turtle> backEnd.turtle.TurtleManager.createTurtleList (List< Double > turtleIds) private
Creates a list of turtles. Begins by checking if there exists a turtle with that id. If it does, it is added to the list, if it does not, a new turtle is made, added to the map, and then the list.
Parameters
turtleNames list of names of the turtles desired
Returns
returns the list of turtles requested
Definition at line 73 of file TurtleManager.java.
References backEnd.turtle.TurtleManager.addNewTurtle().
Referenced by backEnd.turtle.TurtleManager.addTemporaryTurtleList(), and backEnd.turtle.TurtleManager.updateActiveTurtleList().
int backEnd.turtle.TurtleManager.getNumberOfTurtles ()
Returns number of turtles in the manager
Returns
number of turtles
Definition at line 154 of file TurtleManager.java.
Referenced by commands.turtle_commands.TurtlesCommand.executeTurtleCommand().
List<Turtle> backEnd.turtle.TurtleManager.getTurtleList ()
Returns the appropriate turtle list at the top of the stack. If there in an ask command, a temporary turtle list should be at the top of the stack. For anything else it should be the active turtles list.
Returns
list of turtles
Definition at line 129 of file TurtleManager.java.
Referenced by commands.turtle_commands.XCorQuery.execute(), commands.turtle_commands.YCorQuery.execute(), commands.turtle_commands.IsShowingQuery.execute(), commands.turtle_commands.PenDownQuery.execute(), commands.turtle_commands.HeadingQuery.execute(), commands.turtle_commands.StampCommand.executeTurtleCommand(), commands.turtle_commands.SetHeadingCommand.executeTurtleCommand(), commands.turtle_commands.ClearCommand.executeTurtleCommand(), commands.turtle_commands.IdCommand.executeTurtleCommand(), commands.turtle_commands.SetPositionCommand.executeTurtleCommand(), commands.turtle_commands.GetShapeCommand.executeTurtleCommand(), commands.turtle_commands.PenColorCommand.executeTurtleCommand(), commands.turtle_commands.PenUpCommand.executeTurtleCommand(), commands.turtle_commands.HideTurtleCommand.executeTurtleCommand(), commands.turtle_commands.HomeCommand.executeTurtleCommand(), commands.turtle_commands.SetPenColor.executeTurtleCommand(), commands.turtle_commands.SetStrokeSize.executeTurtleCommand(), commands.turtle_commands.ShowTurtleCommand.executeTurtleCommand(), commands.turtle_commands.ClearStampCommand.executeTurtleCommand(), commands.turtle_commands.PenDownCommand.executeTurtleCommand(), commands.turtle_commands.TowardsCommand.executeTurtleCommand(), commands.turtle_commands.SetShapeCommand.executeTurtleCommand(), commands.turtle_commands.BackCommand.executeTurtleCommand(), commands.turtle_commands.LeftCommand.executeTurtleCommand(), commands.turtle_commands.RightCommand.executeTurtleCommand(), and commands.turtle_commands.ForwardCommand.executeTurtleCommand().
void backEnd.turtle.TurtleManager.updateActiveTurtleList (List< Double > turtleIds)
Updates what the current active turtles are for the tell command. Since tell commands overwrite previous tell commands, there is only a need for one active turtle list.
Parameters
turtleNames list of names for turtles to be in active turtles
Definition at line 92 of file TurtleManager.java.
References backEnd.turtle.TurtleManager.createTurtleList().
Referenced by commands.turtle_commands.TellCommand.execute(), and backEnd.Model.setupTurtleManager().
void backEnd.turtle.TurtleManager.updateStoredTurtleLists ()
Updates the stack. If a temporary list was just used it should be removed. If there is only one item in the stack it must be an active turtle list from the tell command. This should not be removed.
Definition at line 138 of file TurtleManager.java.
Referenced by commands.turtle_commands.AskCommand.executeTurtleCommand().
Member Data Documentation
final String backEnd.turtle.TurtleManager.INITIAL_TURTLE = "turtle1" static
Definition at line 22 of file TurtleManager.java.
List<Turtle> backEnd.turtle.TurtleManager.myActiveTurtles private
Definition at line 28 of file TurtleManager.java.
double backEnd.turtle.TurtleManager.myCanvasHeight private
Definition at line 26 of file TurtleManager.java.
Referenced by backEnd.turtle.TurtleManager.addNewTurtle().
double backEnd.turtle.TurtleManager.myCanvasWidth private
Definition at line 25 of file TurtleManager.java.
Referenced by backEnd.turtle.TurtleManager.addNewTurtle().
Stack<List<Turtle> > backEnd.turtle.TurtleManager.myStoredTurtleLists private
Definition at line 27 of file TurtleManager.java.
Map<Double, Turtle> backEnd.turtle.TurtleManager.myTurtles private
Definition at line 24 of file TurtleManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/turtle/TurtleManager.java