slogo_team06: backEnd.VariableManager Class Reference
backEnd.VariableManager Class Reference
Public Member Functions
VariableManager ()
void setVarProperties (File f)
double getVar (String var)
void addVar (String var, String value) throws IOException
boolean checkVarExists (String var)
void pushVarProperties (Map< String, String > variableMap) throws IOException
void popVarProperties () throws IOException
Private Member Functions
void setInitialVarProperties () throws IOException
void writeVarsToFile () throws IOException
Private Attributes
Properties myVariables
Stack< Properties > myStoredVariables
Detailed Description
A variable manager that reads in variable values from properties files or maps for use by commands Also allows variable commands to set values in the properties object. Writes variable values to the properties file.
Author
annamiyajima
Definition at line 25 of file VariableManager.java.
Constructor & Destructor Documentation
backEnd.VariableManager.VariableManager ()
Definition at line 30 of file VariableManager.java.
References backEnd.VariableManager.setInitialVarProperties().
Member Function Documentation
void backEnd.VariableManager.addVar (String var, String value) throws IOException
Adds a variable to the properties file
Parameters
var
value
Exceptions
IOException
Definition at line 90 of file VariableManager.java.
References backEnd.VariableManager.writeVarsToFile().
Referenced by commands.variable_commands.MakeCommand.execute(), and commands.variable_commands.ForCommand.execute().
boolean backEnd.VariableManager.checkVarExists (String var)
Checks if a variable has been defined in the current frame of reference
Parameters
var
Returns
Definition at line 101 of file VariableManager.java.
double backEnd.VariableManager.getVar (String var)
Returns the value of a variable
Parameters
var
Returns
Definition at line 79 of file VariableManager.java.
Referenced by commands.variable_commands.MakeCommand.execute(), and commands.variable_commands.Variable.execute().
void backEnd.VariableManager.popVarProperties () throws IOException
Pops off variable values from a previous frame of reference used to exit loops and user defined commands
Exceptions
IOException
Definition at line 129 of file VariableManager.java.
References backEnd.VariableManager.writeVarsToFile().
Referenced by commands.variable_commands.DoTimesCommand.execute(), and commands.variable_commands.UserDefinedCommand.execute().
void backEnd.VariableManager.pushVarProperties (Map< String, String > variableMap) throws IOException
Creates a new frame of variables to be defined and read Used in user defined commands and loops
Parameters
variableMap
Exceptions
IOException
Definition at line 112 of file VariableManager.java.
References backEnd.VariableManager.writeVarsToFile().
Referenced by commands.variable_commands.DoTimesCommand.execute(), and commands.variable_commands.UserDefinedCommand.execute().
void backEnd.VariableManager.setInitialVarProperties () throws IOException private
Sets variable properties file to default values
Exceptions
IOException
Definition at line 46 of file VariableManager.java.
Referenced by backEnd.VariableManager.VariableManager().
void backEnd.VariableManager.setVarProperties (File f)
Sets variable properties from a user defined file
Parameters
f
Definition at line 56 of file VariableManager.java.
Referenced by backEnd.Model.setVariableProperties().
void backEnd.VariableManager.writeVarsToFile () throws IOException private
Definition at line 134 of file VariableManager.java.
Referenced by backEnd.VariableManager.addVar(), backEnd.VariableManager.popVarProperties(), and backEnd.VariableManager.pushVarProperties().
Member Data Documentation
Stack<Properties> backEnd.VariableManager.myStoredVariables private
Definition at line 28 of file VariableManager.java.
Properties backEnd.VariableManager.myVariables private
Definition at line 27 of file VariableManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/VariableManager.java