slogo_team06: backEnd.turtle.TurtleProperties Class Reference
backEnd.turtle.TurtleProperties Class Reference
Public Member Functions
TurtleProperties (TurtlePoint position, DoubleProperty orientation, BooleanProperty isPenDown, BooleanProperty linesCleared, BooleanProperty isVisible, DoubleProperty stampCount, Pen pen, DoubleProperty shapeIndex, BooleanProperty activity)
DoubleProperty getXPosition ()
DoubleProperty getYPosition ()
DoubleProperty getOrientation ()
BooleanProperty getIsPenDown ()
BooleanProperty getLinesCleared ()
BooleanProperty getVisibility ()
DoubleProperty getStampCount ()
DoubleProperty getPenColorIndex ()
DoubleProperty getPenSize ()
DoubleProperty getShapeIndex ()
BooleanProperty getActivity ()
Private Attributes
TurtlePoint myPosition
DoubleProperty myOrientation
BooleanProperty myPenState
BooleanProperty myLinesCleared
BooleanProperty myVisibility
DoubleProperty myStampCount
DoubleProperty myPenColorIndex
DoubleProperty myPenSize
DoubleProperty myShapeIndex
BooleanProperty myActivity
Detailed Description
Passive data object used to hold properties about Turtle that later are bound to TurtleView. Has no behavior on its own. Was created to replace need for list or map to pass properties from model to view. User-created data structure to replace already made data structure (e.g., list, map)
Author
Eli Lichtenberg
Definition at line 15 of file TurtleProperties.java.
Constructor & Destructor Documentation
backEnd.turtle.TurtleProperties.TurtleProperties (TurtlePoint position, DoubleProperty orientation, BooleanProperty isPenDown, BooleanProperty linesCleared, BooleanProperty isVisible, DoubleProperty stampCount, Pen pen, DoubleProperty shapeIndex, BooleanProperty activity)
Definition at line 28 of file TurtleProperties.java.
References backEnd.turtle.Pen.getMyPenColorProperty(), and backEnd.turtle.Pen.getMyPenSize().
Member Function Documentation
BooleanProperty backEnd.turtle.TurtleProperties.getActivity ()
Definition at line 92 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myActivity.
Referenced by frontEnd.TurtleView.bindProperties().
BooleanProperty backEnd.turtle.TurtleProperties.getIsPenDown ()
Definition at line 64 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myPenState.
Referenced by frontEnd.TurtleView.bindProperties().
BooleanProperty backEnd.turtle.TurtleProperties.getLinesCleared ()
Definition at line 68 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myLinesCleared.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getOrientation ()
Definition at line 56 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myOrientation.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getPenColorIndex ()
Definition at line 80 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myPenColorIndex.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getPenSize ()
Definition at line 84 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myPenSize.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getShapeIndex ()
Definition at line 88 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myShapeIndex.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getStampCount ()
Definition at line 76 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myStampCount.
Referenced by frontEnd.TurtleView.bindProperties().
BooleanProperty backEnd.turtle.TurtleProperties.getVisibility ()
Definition at line 72 of file TurtleProperties.java.
References backEnd.turtle.TurtleProperties.myVisibility.
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getXPosition ()
Definition at line 44 of file TurtleProperties.java.
References backEnd.turtle.TurtlePoint.getBindableX().
Referenced by frontEnd.TurtleView.bindProperties().
DoubleProperty backEnd.turtle.TurtleProperties.getYPosition ()
Definition at line 48 of file TurtleProperties.java.
References backEnd.turtle.TurtlePoint.getBindableY().
Referenced by frontEnd.TurtleView.bindProperties().
Member Data Documentation
BooleanProperty backEnd.turtle.TurtleProperties.myActivity private
Definition at line 26 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getActivity().
BooleanProperty backEnd.turtle.TurtleProperties.myLinesCleared private
Definition at line 20 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getLinesCleared().
DoubleProperty backEnd.turtle.TurtleProperties.myOrientation private
Definition at line 18 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getOrientation().
DoubleProperty backEnd.turtle.TurtleProperties.myPenColorIndex private
Definition at line 23 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getPenColorIndex().
DoubleProperty backEnd.turtle.TurtleProperties.myPenSize private
Definition at line 24 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getPenSize().
BooleanProperty backEnd.turtle.TurtleProperties.myPenState private
Definition at line 19 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getIsPenDown().
TurtlePoint backEnd.turtle.TurtleProperties.myPosition private
Definition at line 17 of file TurtleProperties.java.
DoubleProperty backEnd.turtle.TurtleProperties.myShapeIndex private
Definition at line 25 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getShapeIndex().
DoubleProperty backEnd.turtle.TurtleProperties.myStampCount private
Definition at line 22 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getStampCount().
BooleanProperty backEnd.turtle.TurtleProperties.myVisibility private
Definition at line 21 of file TurtleProperties.java.
Referenced by backEnd.turtle.TurtleProperties.getVisibility().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/turtle/TurtleProperties.java