slogo_team06: panels.ParameterPanel Class Reference
panels.ParameterPanel Class Reference
Public Member Functions
ParameterPanel (double width, double height, Controller controller) throws IOException
void addToHistory (String script)
void updateVariables () throws IOException
Private Member Functions
void setupTitledPanes (Controller controller) throws IOException
void addDecorations ()
Private Attributes
DisplayTitlePane myDisplayTitlePane
HistoryTitlePane myHistoryTitlePane
ControlTitlePane myControlTitlePane
CommandTitlePane myCommandTitlePane
VariableTitlePane myVariableTitlePane
HelpTitlePane myHelpTitlePane
LoadVariablesTitlePane myLoadPropertiesTitlePane
Detailed Description
Definition at line 20 of file ParameterPanel.java.
Constructor & Destructor Documentation
panels.ParameterPanel.ParameterPanel (double width, double height, Controller controller) throws IOException
Definition at line 30 of file ParameterPanel.java.
References panels.ParameterPanel.addDecorations(), and panels.ParameterPanel.setupTitledPanes().
Member Function Documentation
void panels.ParameterPanel.addDecorations () private
Definition at line 70 of file ParameterPanel.java.
Referenced by panels.ParameterPanel.ParameterPanel().
void panels.ParameterPanel.addToHistory (String script)
Definition at line 52 of file ParameterPanel.java.
References titlePanes.HistoryTitlePane.addToHistory().
Referenced by frontEnd.View.addToHistory().
void panels.ParameterPanel.setupTitledPanes (Controller controller) throws IOException private
Definition at line 60 of file ParameterPanel.java.
Referenced by panels.ParameterPanel.ParameterPanel().
void panels.ParameterPanel.updateVariables () throws IOException
Definition at line 77 of file ParameterPanel.java.
References titlePanes.VariableTitlePane.updateVariables().
Referenced by frontEnd.View.updateVariables().
Member Data Documentation
CommandTitlePane panels.ParameterPanel.myCommandTitlePane private
Definition at line 25 of file ParameterPanel.java.
ControlTitlePane panels.ParameterPanel.myControlTitlePane private
Definition at line 24 of file ParameterPanel.java.
DisplayTitlePane panels.ParameterPanel.myDisplayTitlePane private
Definition at line 22 of file ParameterPanel.java.
HelpTitlePane panels.ParameterPanel.myHelpTitlePane private
Definition at line 27 of file ParameterPanel.java.
HistoryTitlePane panels.ParameterPanel.myHistoryTitlePane private
Definition at line 23 of file ParameterPanel.java.
LoadVariablesTitlePane panels.ParameterPanel.myLoadPropertiesTitlePane private
Definition at line 28 of file ParameterPanel.java.
VariableTitlePane panels.ParameterPanel.myVariableTitlePane private
Definition at line 26 of file ParameterPanel.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/panels/ParameterPanel.java