slogo_team06: commands.variable_commands.ForCommand Class Reference
commands.variable_commands.ForCommand Class Reference
Public Member Functions
ForCommand (VariableManager manager)
double execute ()
String toString ()
Public Member Functions inherited from commands.templates.TwoChildCommand
TwoChildCommand (VariableManager manager)
String toString ()
void initializeCommand (Model model)
Public Member Functions inherited from commands.templates.Command
Command (VariableManager manager)
abstract double execute ()
abstract String toString ()
List< Command > getMyChildren ()
void addChild (Command c)
int getNumChildrenNeeded ()
abstract void initializeCommand (Model model)
Static Public Attributes
static final int THIRD_CHILD = 3
Static Public Attributes inherited from commands.templates.TwoChildCommand
static final int NUM_CHILDREN = 2
Private Attributes
Command myForList
Additional Inherited Members
Protected Member Functions inherited from commands.templates.Command
void setNumChildren (int numChildren)
void setValue (Double value)
double getValue ()
VariableManager getVariableManager ()
Detailed Description
A for loop command.
Input format: for [ :x 1 10 1 ] [ forward :x ]
Author
annamiyajima
Definition at line 17 of file ForCommand.java.
Constructor & Destructor Documentation
commands.variable_commands.ForCommand.ForCommand (VariableManager manager)
Definition at line 22 of file ForCommand.java.
Member Function Documentation
double commands.variable_commands.ForCommand.execute ()
Definition at line 28 of file ForCommand.java.
References backEnd.VariableManager.addVar(), commands.templates.Command.getMyChildren(), commands.templates.Command.getVariableManager(), commands.variable_commands.ForCommand.myForList, and commands.variable_commands.ForCommand.toString().
String commands.variable_commands.ForCommand.toString ()
Definition at line 52 of file ForCommand.java.
References commands.templates.Command.getMyChildren().
Referenced by commands.variable_commands.ForCommand.execute().
Member Data Documentation
Command commands.variable_commands.ForCommand.myForList private
Definition at line 20 of file ForCommand.java.
Referenced by commands.variable_commands.ForCommand.execute().
final int commands.variable_commands.ForCommand.THIRD_CHILD = 3 static
Definition at line 19 of file ForCommand.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/commands/variable_commands/ForCommand.java