slogo_team06: commands.turtle_commands.PenDownCommand Class Reference
commands.turtle_commands.PenDownCommand Class Reference
Public Member Functions
PenDownCommand (VariableManager manager)
double execute ()
void executeTurtleCommand (TurtleManager turtleManager)
String toString ()
Public Member Functions inherited from commands.templates.TurtleCommand
TurtleCommand (VariableManager manager)
abstract void executeTurtleCommand (TurtleManager turtleManager)
void initializeCommand (Model model)
Public Member Functions inherited from commands.templates.Command
Command (VariableManager manager)
abstract double execute ()
abstract String toString ()
List< Command > getMyChildren ()
void addChild (Command c)
int getNumChildrenNeeded ()
abstract void initializeCommand (Model model)
Static Public Attributes
static final int PEN_DOWN = 1
static final int NUM_CHILDREN = 0
Additional Inherited Members
Protected Member Functions inherited from commands.templates.TurtleCommand
TurtleManager getMyTurtleManager ()
Protected Member Functions inherited from commands.templates.Command
void setNumChildren (int numChildren)
void setValue (Double value)
double getValue ()
VariableManager getVariableManager ()
Detailed Description
Command to put the pen down
Author
Ethan Chang
Definition at line 16 of file PenDownCommand.java.
Constructor & Destructor Documentation
commands.turtle_commands.PenDownCommand.PenDownCommand (VariableManager manager)
Definition at line 20 of file PenDownCommand.java.
References commands.templates.Command.setNumChildren().
Member Function Documentation
double commands.turtle_commands.PenDownCommand.execute ()
Definition at line 26 of file PenDownCommand.java.
References commands.turtle_commands.PenDownCommand.executeTurtleCommand(), commands.templates.TurtleCommand.getMyTurtleManager(), and commands.turtle_commands.PenDownCommand.PEN_DOWN.
void commands.turtle_commands.PenDownCommand.executeTurtleCommand (TurtleManager turtleManager)
Definition at line 32 of file PenDownCommand.java.
References backEnd.turtle.TurtleManager.getTurtleList().
Referenced by commands.turtle_commands.PenDownCommand.execute().
String commands.turtle_commands.PenDownCommand.toString ()
Definition at line 40 of file PenDownCommand.java.
Member Data Documentation
final int commands.turtle_commands.PenDownCommand.NUM_CHILDREN = 0 static
Definition at line 18 of file PenDownCommand.java.
final int commands.turtle_commands.PenDownCommand.PEN_DOWN = 1 static
Definition at line 17 of file PenDownCommand.java.
Referenced by commands.turtle_commands.PenDownCommand.execute().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/commands/turtle_commands/PenDownCommand.java