slogo_team06: commands.twochildren.OrCommand Class Reference
commands.twochildren.OrCommand Class Reference
Public Member Functions
OrCommand (VariableManager manager)
double execute ()
String toString ()
Public Member Functions inherited from commands.templates.TwoChildCommand
TwoChildCommand (VariableManager manager)
String toString ()
void initializeCommand (Model model)
Public Member Functions inherited from commands.templates.Command
Command (VariableManager manager)
abstract double execute ()
abstract String toString ()
List< Command > getMyChildren ()
void addChild (Command c)
int getNumChildrenNeeded ()
abstract void initializeCommand (Model model)
Additional Inherited Members
Static Public Attributes inherited from commands.templates.TwoChildCommand
static final int NUM_CHILDREN = 2
Protected Member Functions inherited from commands.templates.Command
void setNumChildren (int numChildren)
void setValue (Double value)
double getValue ()
VariableManager getVariableManager ()
Detailed Description
Checks if either child is equal to one
Author
Ethan Chang
Definition at line 12 of file OrCommand.java.
Constructor & Destructor Documentation
commands.twochildren.OrCommand.OrCommand (VariableManager manager)
Definition at line 14 of file OrCommand.java.
Member Function Documentation
double commands.twochildren.OrCommand.execute ()
Definition at line 19 of file OrCommand.java.
References commands.templates.Command.getMyChildren().
Referenced by commands.twochildren.OrCommand.toString().
String commands.twochildren.OrCommand.toString ()
Definition at line 25 of file OrCommand.java.
References commands.twochildren.OrCommand.execute().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/commands/twochildren/OrCommand.java