slogo_team06: backEnd.Controller Class Reference
backEnd.Controller Class Reference
Public Member Functions
Controller (Model model, View view)
void runScript (String script)
void move10 (String direction)
void changeBackgroundColor (Color c)
void changePenColor (Color c)
void changeTurtleImage (File f)
void toggleGridLines ()
void setVariableProperties (File f)
void addTextToScript (String translatedCommand)
Public Attributes
EventHandler< MouseEvent > myMouseListener
EventHandler< KeyEvent > myKeyListener
Private Member Functions
void buildMouseListener ()
void buildKeyListener ()
Private Attributes
Model myModel
View myView
Detailed Description
Author
Brian Bolze
Definition at line 18 of file Controller.java.
Constructor & Destructor Documentation
backEnd.Controller.Controller (Model model, View view)
Definition at line 31 of file Controller.java.
References frontEnd.View.addControllerAndSetupGui(), frontEnd.View.bindToModelProperties(), backEnd.Controller.buildKeyListener(), backEnd.Controller.buildMouseListener(), backEnd.Model.getBackgroundIndex(), backEnd.Model.getPaletteArguments(), and backEnd.Model.setupTurtleManager().
Member Function Documentation
void backEnd.Controller.addTextToScript (String translatedCommand)
Definition at line 125 of file Controller.java.
References frontEnd.View.addTextToScript().
Referenced by titlePanes.CommandTitlePane.CommandTitlePane().
void backEnd.Controller.buildKeyListener () private
Definition at line 101 of file Controller.java.
References backEnd.Controller.move10().
Referenced by backEnd.Controller.Controller().
void backEnd.Controller.buildMouseListener () private
Definition at line 90 of file Controller.java.
Referenced by backEnd.Controller.Controller().
void backEnd.Controller.changeBackgroundColor (Color c)
Definition at line 70 of file Controller.java.
References frontEnd.View.changeBackgroundColor().
void backEnd.Controller.changePenColor (Color c)
Definition at line 74 of file Controller.java.
References frontEnd.View.changePenColor().
Referenced by titlePanes.ControlTitlePane.makePenColorBox().
void backEnd.Controller.changeTurtleImage (File f)
Definition at line 78 of file Controller.java.
References frontEnd.View.changeTurtleImage().
Referenced by titlePanes.DisplayTitlePane.openFile().
void backEnd.Controller.move10 (String direction)
Called by keys and buttons
Parameters
The base command that is being executed
Definition at line 63 of file Controller.java.
References main.ResourceFinder.getMyLanguageResources(), and backEnd.Controller.runScript().
Referenced by backEnd.Controller.buildKeyListener(), and titlePanes.ControlTitlePane.handle().
void backEnd.Controller.runScript (String script)
Definition at line 45 of file Controller.java.
References frontEnd.View.addToHistory(), frontEnd.View.printException(), backEnd.Model.runScript(), and frontEnd.View.updateVariables().
Referenced by panels.ScriptPanel.handler(), titlePanes.ControlTitlePane.makeLocationFields(), and backEnd.Controller.move10().
void backEnd.Controller.setVariableProperties (File f)
Definition at line 86 of file Controller.java.
References backEnd.Model.setVariableProperties().
Referenced by titlePanes.LoadVariablesTitlePane.openFile().
void backEnd.Controller.toggleGridLines ()
Definition at line 82 of file Controller.java.
References frontEnd.View.toggleGridLines().
Referenced by titlePanes.DisplayTitlePane.makeGridLinesBox().
Member Data Documentation
EventHandler<KeyEvent> backEnd.Controller.myKeyListener
Definition at line 26 of file Controller.java.
Referenced by frontEnd.Workspace.getKeyListener().
Model backEnd.Controller.myModel private
Definition at line 28 of file Controller.java.
EventHandler<MouseEvent> backEnd.Controller.myMouseListener
Used by Workspace to attach the appropriate MouseEvent EventHandler to the stage
Definition at line 24 of file Controller.java.
Referenced by frontEnd.Workspace.getMouseListener().
View backEnd.Controller.myView private
Definition at line 29 of file Controller.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/Controller.java