slogo_team06: commands.CommandFactory Class Reference
commands.CommandFactory Class Reference
Public Member Functions
CommandFactory ()
boolean isNumeric (String str)
Command buildCommand (String type, Model model, VariableManager variableManager)
Private Member Functions
boolean checkLanguage (String type)
boolean checkVar (String type)
String checkCaps (String type)
boolean checkUserCommand (String type, Map< String, Command > commandsMap)
Private Attributes
String myClassKey
Detailed Description
This factory is part of the command pattern implementation. It contains a method called buildCommand which takes in a String type and uses this String to create the type of command requested.
Definition at line 26 of file CommandFactory.java.
Constructor & Destructor Documentation
commands.CommandFactory.CommandFactory ()
Definition at line 30 of file CommandFactory.java.
Member Function Documentation
Command commands.CommandFactory.buildCommand (String type, Model model, VariableManager variableManager)
If a command is valid, create an instance of that command and return it. If it is a constant, return a constant command instead. If it is invalid, return an error
Parameters
type Command being tested
Returns
Either the type of command requested, or an exception
Definition at line 97 of file CommandFactory.java.
References commands.CommandFactory.checkCaps(), commands.CommandFactory.checkLanguage(), commands.CommandFactory.checkUserCommand(), commands.CommandFactory.checkVar(), backEnd.Model.getCommandsMap(), commands.templates.Command.initializeCommand(), and commands.CommandFactory.isNumeric().
Referenced by backEnd.Parser.makeTree().
String commands.CommandFactory.checkCaps (String type) private
PUBLIC FOR TESTING PURPOSES make all letters lower case so input is not case sensative
Parameters
type
Returns
Definition at line 74 of file CommandFactory.java.
Referenced by commands.CommandFactory.buildCommand().
boolean commands.CommandFactory.checkLanguage (String type) private
Searches to see if the command given is can be found in the selected language properties file. If it can, return true, if not false.
Parameters
type command type being checked
Returns
Return true if the command is valid
Definition at line 42 of file CommandFactory.java.
References main.ResourceFinder.getMyLanguageResources().
Referenced by commands.CommandFactory.buildCommand().
boolean commands.CommandFactory.checkUserCommand (String type, Map< String, Command > commandsMap) private
Checks if the command has been previously defined by the user
Parameters
type
Returns
Definition at line 84 of file CommandFactory.java.
Referenced by commands.CommandFactory.buildCommand().
boolean commands.CommandFactory.checkVar (String type) private
Definition at line 58 of file CommandFactory.java.
Referenced by commands.CommandFactory.buildCommand().
boolean commands.CommandFactory.isNumeric (String str)
Definition at line 62 of file CommandFactory.java.
Referenced by commands.CommandFactory.buildCommand().
Member Data Documentation
String commands.CommandFactory.myClassKey private
Definition at line 28 of file CommandFactory.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/commands/CommandFactory.java