slogo_team06: backEnd.turtle.TurtlePoint Class Reference
backEnd.turtle.TurtlePoint Class Reference
Public Member Functions
TurtlePoint (double x, double y)
double getX ()
double getY ()
DoubleProperty getBindableX ()
DoubleProperty getBindableY ()
void setX (double x)
void setY (double y)
void set (double x, double y)
void set (Point2D p)
void set (TurtlePoint tp)
double distance (double x1, double y1)
double distance (Point2D p)
double distance (TurtlePoint tp)
Private Attributes
Point2D myPosition
DoubleProperty myXPosition
DoubleProperty myYPosition
Detailed Description
Similar to Point2D, but also holds DoubleProperties to enable binding between front-end and back-end. Unlike Point2D, can set new x and y of TurtlePoint without needing to construct TurtlePoint
Author
Eli Lichtenberg
Definition at line 15 of file TurtlePoint.java.
Constructor & Destructor Documentation
backEnd.turtle.TurtlePoint.TurtlePoint (double x, double y)
Definition at line 21 of file TurtlePoint.java.
Member Function Documentation
double backEnd.turtle.TurtlePoint.distance (double x1, double y1)
Definition at line 76 of file TurtlePoint.java.
Referenced by backEnd.turtle.Turtle.goHome(), and backEnd.turtle.Turtle.goTo().
double backEnd.turtle.TurtlePoint.distance (Point2D p)
Definition at line 80 of file TurtlePoint.java.
double backEnd.turtle.TurtlePoint.distance (TurtlePoint tp)
Definition at line 85 of file TurtlePoint.java.
References backEnd.turtle.TurtlePoint.getX(), and backEnd.turtle.TurtlePoint.getY().
DoubleProperty backEnd.turtle.TurtlePoint.getBindableX ()
Definition at line 38 of file TurtlePoint.java.
References backEnd.turtle.TurtlePoint.myXPosition.
Referenced by backEnd.turtle.TurtleProperties.getXPosition().
DoubleProperty backEnd.turtle.TurtlePoint.getBindableY ()
Definition at line 42 of file TurtlePoint.java.
References backEnd.turtle.TurtlePoint.myYPosition.
Referenced by backEnd.turtle.TurtleProperties.getYPosition().
double backEnd.turtle.TurtlePoint.getX ()
Definition at line 30 of file TurtlePoint.java.
Referenced by backEnd.turtle.TurtlePoint.distance(), backEnd.turtle.Turtle.getMyX(), backEnd.turtle.TurtlePoint.set(), backEnd.turtle.Turtle.toroidalMovement(), backEnd.turtle.Turtle.turnTowards(), and backEnd.turtle.Turtle.Turtle().
double backEnd.turtle.TurtlePoint.getY ()
Definition at line 34 of file TurtlePoint.java.
Referenced by backEnd.turtle.TurtlePoint.distance(), backEnd.turtle.Turtle.getMyY(), backEnd.turtle.TurtlePoint.set(), backEnd.turtle.Turtle.toroidalMovement(), backEnd.turtle.Turtle.turnTowards(), and backEnd.turtle.Turtle.Turtle().
void backEnd.turtle.TurtlePoint.set (double x, double y)
Definition at line 57 of file TurtlePoint.java.
Referenced by backEnd.turtle.Turtle.goHome(), backEnd.turtle.Turtle.goTo(), and backEnd.turtle.Turtle.setPosition().
void backEnd.turtle.TurtlePoint.set (Point2D p)
Definition at line 63 of file TurtlePoint.java.
void backEnd.turtle.TurtlePoint.set (TurtlePoint tp)
Definition at line 69 of file TurtlePoint.java.
References backEnd.turtle.TurtlePoint.getX(), and backEnd.turtle.TurtlePoint.getY().
void backEnd.turtle.TurtlePoint.setX (double x)
Definition at line 47 of file TurtlePoint.java.
void backEnd.turtle.TurtlePoint.setY (double y)
Definition at line 52 of file TurtlePoint.java.
Member Data Documentation
Point2D backEnd.turtle.TurtlePoint.myPosition private
Definition at line 17 of file TurtlePoint.java.
DoubleProperty backEnd.turtle.TurtlePoint.myXPosition private
Definition at line 18 of file TurtlePoint.java.
Referenced by backEnd.turtle.TurtlePoint.getBindableX().
DoubleProperty backEnd.turtle.TurtlePoint.myYPosition private
Definition at line 19 of file TurtlePoint.java.
Referenced by backEnd.turtle.TurtlePoint.getBindableY().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/turtle/TurtlePoint.java