slogo_team06: frontEnd.TurtleView Class Reference
frontEnd.TurtleView Class Reference
Public Member Functions
TurtleView (TurtleProperties tProps, double boundingWidth, double boundingHeight, ImageView imageView, Properties cProps) throws IOException
ImageView getImageView ()
Image getImage ()
Group getPenLines ()
Group getStamps ()
void setImage (Image image)
void drawLine (Point2D endPoint)
void drawStamp ()
void changePenColor (Color c)
void setTurtleX (double x)
void setTurtleY (double y)
void setOrientation (double orientation)
boolean penIsDown ()
Private Member Functions
void initializeBindableProperties ()
void addListeners ()
void addActivityListener ()
void addShapeIndexListener ()
void addPenColorIndexListener ()
void addStampCountListener ()
void addVisibilityListener ()
void addLinesClearedListener ()
void addOrientationListener ()
void addYPositionListener ()
void addXPositionListener ()
boolean facingHorizontal ()
void bindProperties (TurtleProperties tProps)
Private Attributes
ImageView myImageView
Group myPenLines
Group myStamps
Drawer myDrawer
Color myPenColor
double myLineStartX
double myLineStartY
DoubleProperty myXPosition
DoubleProperty myYPosition
DoubleProperty myOrientation
BooleanProperty myPenDown
BooleanProperty myLinesCleared
BooleanProperty myVisibility
DoubleProperty myStampCount
DoubleProperty myPenColorIndex
DoubleProperty myPenSize
DoubleProperty myShapeIndex
BooleanProperty myActivity
Properties myColorProperties
ResourceBundle myImageResources
Static Private Attributes
static final double INACTIVE_OPACITY = .4
static final int ACTIVE_OPACITY = 1
static final int HALF_CIRCLE = 180
static final int RIGHT_ORIENTATION = 90
Detailed Description
Graphical representation of a turtle on the canvas. Holds image of the turtle, lines drawn by the turtle's pen, stamps by the turtle, and properties necessary to display these.
Author
Brian Bolze
Ethan Chang
Eli Lichtenberg
Anna Miyajima
Definition at line 34 of file TurtleView.java.
Constructor & Destructor Documentation
frontEnd.TurtleView.TurtleView (TurtleProperties tProps, double boundingWidth, double boundingHeight, ImageView imageView, Properties cProps) throws IOException
Constructor for TurtleView. Initializes properties to bind with properties of corresponding turtle in backend.
Parameters
tProps TurtleProperties data object holding bindable properties
boundingWidth Bounding width of canvas
boundingHeight Bounding height of canvas
imageView ImageView used to represent turtle
cProps Properties file holding color index information
Exceptions
IOException
Definition at line 74 of file TurtleView.java.
References frontEnd.TurtleView.addListeners(), frontEnd.TurtleView.bindProperties(), frontEnd.TurtleView.getImage(), and frontEnd.TurtleView.initializeBindableProperties().
Member Function Documentation
void frontEnd.TurtleView.addActivityListener () private
Definition at line 220 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addLinesClearedListener () private
Definition at line 285 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addListeners () private
Definition at line 208 of file TurtleView.java.
References frontEnd.TurtleView.addActivityListener(), frontEnd.TurtleView.addLinesClearedListener(), frontEnd.TurtleView.addOrientationListener(), frontEnd.TurtleView.addPenColorIndexListener(), frontEnd.TurtleView.addShapeIndexListener(), frontEnd.TurtleView.addStampCountListener(), frontEnd.TurtleView.addVisibilityListener(), frontEnd.TurtleView.addXPositionListener(), and frontEnd.TurtleView.addYPositionListener().
Referenced by frontEnd.TurtleView.TurtleView().
void frontEnd.TurtleView.addOrientationListener () private
Definition at line 297 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addPenColorIndexListener () private
Definition at line 247 of file TurtleView.java.
References frontEnd.TurtleView.changePenColor().
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addShapeIndexListener () private
Definition at line 235 of file TurtleView.java.
References frontEnd.TurtleView.setImage().
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addStampCountListener () private
Definition at line 260 of file TurtleView.java.
References frontEnd.TurtleView.drawStamp().
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addVisibilityListener () private
Definition at line 275 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addXPositionListener () private
Definition at line 323 of file TurtleView.java.
References frontEnd.TurtleView.drawLine(), frontEnd.TurtleView.facingHorizontal(), and frontEnd.TurtleView.setTurtleX().
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.addYPositionListener () private
Definition at line 307 of file TurtleView.java.
References frontEnd.TurtleView.drawLine(), and frontEnd.TurtleView.setTurtleY().
Referenced by frontEnd.TurtleView.addListeners().
void frontEnd.TurtleView.bindProperties (TurtleProperties tProps) private
Definition at line 356 of file TurtleView.java.
References backEnd.turtle.TurtleProperties.getActivity(), backEnd.turtle.TurtleProperties.getIsPenDown(), backEnd.turtle.TurtleProperties.getLinesCleared(), backEnd.turtle.TurtleProperties.getOrientation(), backEnd.turtle.TurtleProperties.getPenColorIndex(), backEnd.turtle.TurtleProperties.getPenSize(), backEnd.turtle.TurtleProperties.getShapeIndex(), backEnd.turtle.TurtleProperties.getStampCount(), backEnd.turtle.TurtleProperties.getVisibility(), backEnd.turtle.TurtleProperties.getXPosition(), and backEnd.turtle.TurtleProperties.getYPosition().
Referenced by frontEnd.TurtleView.TurtleView().
void frontEnd.TurtleView.changePenColor (Color c)
Changes color of turtle's pen.
Parameters
c Color by which to change turtle's pen
Definition at line 177 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addPenColorIndexListener(), and frontEnd.TurtleCanvas.changePenColor().
void frontEnd.TurtleView.drawLine (Point2D endPoint)
Draws a line from turtle's previous position to current position.
Parameters
endPoint Current position of turtle where line will end
Definition at line 155 of file TurtleView.java.
References drawer.Drawer.makeLine().
Referenced by frontEnd.TurtleView.addXPositionListener(), and frontEnd.TurtleView.addYPositionListener().
void frontEnd.TurtleView.drawStamp ()
Places a stamp on the canvas with image identical to the image used to represent the turtle.
Definition at line 165 of file TurtleView.java.
References frontEnd.TurtleView.getImage().
Referenced by frontEnd.TurtleView.addStampCountListener().
boolean frontEnd.TurtleView.facingHorizontal () private
Definition at line 341 of file TurtleView.java.
References frontEnd.TurtleView.HALF_CIRCLE.
Referenced by frontEnd.TurtleView.addXPositionListener().
Image frontEnd.TurtleView.getImage ()
Returns the Image used in the ImageView of the TurtleView.
Returns
Image representing turtle
Definition at line 123 of file TurtleView.java.
Referenced by frontEnd.TurtleView.drawStamp(), frontEnd.TurtleView.setTurtleX(), frontEnd.TurtleView.setTurtleY(), and frontEnd.TurtleView.TurtleView().
ImageView frontEnd.TurtleView.getImageView ()
Returns the ImageView used to represent turtle.
Returns
ImageView of TurtleView
Definition at line 115 of file TurtleView.java.
References frontEnd.TurtleView.myImageView.
Referenced by frontEnd.TurtleCanvas.addTurtle().
Group frontEnd.TurtleView.getPenLines ()
Returns group holding lines drawn by turtle's pen.
Returns
Pen lines group
Definition at line 131 of file TurtleView.java.
References frontEnd.TurtleView.myPenLines.
Referenced by frontEnd.TurtleCanvas.addTurtle().
Group frontEnd.TurtleView.getStamps ()
Returns group holding stamps placed by turtle.
Returns
Stamps group
Definition at line 139 of file TurtleView.java.
References frontEnd.TurtleView.myStamps.
Referenced by frontEnd.TurtleCanvas.addTurtle().
void frontEnd.TurtleView.initializeBindableProperties () private
Definition at line 95 of file TurtleView.java.
Referenced by frontEnd.TurtleView.TurtleView().
boolean frontEnd.TurtleView.penIsDown ()
Returns true if turtle's pen is down and writing
Returns
Boolean for whether pen is down or up
Definition at line 352 of file TurtleView.java.
void frontEnd.TurtleView.setImage (Image image)
Sets image of turtle.
Parameters
image Image used to represent turtle
Definition at line 147 of file TurtleView.java.
Referenced by frontEnd.TurtleView.addShapeIndexListener(), and frontEnd.TurtleCanvas.changeTurtleImage().
void frontEnd.TurtleView.setOrientation (double orientation)
Sets orientation of TurtleView.
Parameters
orientation New orientation
Definition at line 203 of file TurtleView.java.
void frontEnd.TurtleView.setTurtleX (double x)
Moves TurtleView to new horizontal position.
Parameters
x New horizontal position
Definition at line 185 of file TurtleView.java.
References frontEnd.TurtleView.getImage().
Referenced by frontEnd.TurtleView.addXPositionListener().
void frontEnd.TurtleView.setTurtleY (double y)
Moves TurtleView to new vertical position.
Parameters
y New vertical position
Definition at line 194 of file TurtleView.java.
References frontEnd.TurtleView.getImage().
Referenced by frontEnd.TurtleView.addYPositionListener().
Member Data Documentation
final int frontEnd.TurtleView.ACTIVE_OPACITY = 1 static private
Definition at line 37 of file TurtleView.java.
final int frontEnd.TurtleView.HALF_CIRCLE = 180 static private
Definition at line 38 of file TurtleView.java.
Referenced by frontEnd.TurtleView.facingHorizontal().
final double frontEnd.TurtleView.INACTIVE_OPACITY = .4 static private
Definition at line 36 of file TurtleView.java.
BooleanProperty frontEnd.TurtleView.myActivity private
Definition at line 58 of file TurtleView.java.
Properties frontEnd.TurtleView.myColorProperties private
Definition at line 60 of file TurtleView.java.
Drawer frontEnd.TurtleView.myDrawer private
Definition at line 43 of file TurtleView.java.
ResourceBundle frontEnd.TurtleView.myImageResources private
Definition at line 61 of file TurtleView.java.
ImageView frontEnd.TurtleView.myImageView private
Definition at line 40 of file TurtleView.java.
Referenced by frontEnd.TurtleView.getImageView().
BooleanProperty frontEnd.TurtleView.myLinesCleared private
Definition at line 52 of file TurtleView.java.
double frontEnd.TurtleView.myLineStartX private
Definition at line 46 of file TurtleView.java.
double frontEnd.TurtleView.myLineStartY private
Definition at line 47 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myOrientation private
Definition at line 50 of file TurtleView.java.
Color frontEnd.TurtleView.myPenColor private
Definition at line 44 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myPenColorIndex private
Definition at line 55 of file TurtleView.java.
BooleanProperty frontEnd.TurtleView.myPenDown private
Definition at line 51 of file TurtleView.java.
Group frontEnd.TurtleView.myPenLines private
Definition at line 41 of file TurtleView.java.
Referenced by frontEnd.TurtleView.getPenLines().
DoubleProperty frontEnd.TurtleView.myPenSize private
Definition at line 56 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myShapeIndex private
Definition at line 57 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myStampCount private
Definition at line 54 of file TurtleView.java.
Group frontEnd.TurtleView.myStamps private
Definition at line 42 of file TurtleView.java.
Referenced by frontEnd.TurtleView.getStamps().
BooleanProperty frontEnd.TurtleView.myVisibility private
Definition at line 53 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myXPosition private
Definition at line 48 of file TurtleView.java.
DoubleProperty frontEnd.TurtleView.myYPosition private
Definition at line 49 of file TurtleView.java.
final int frontEnd.TurtleView.RIGHT_ORIENTATION = 90 static private
Definition at line 39 of file TurtleView.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/frontEnd/TurtleView.java