slogo_team06: backEnd.Parser Class Reference
backEnd.Parser Class Reference
Public Member Functions
Parser (CommandFactory commandFactory)
Command makeTree (String commandName, Model model, VariableManager variableManager, Map< String, Command > commandsmap)
Static Public Attributes
static final String CONSTANT_REGEX = "-?[0-9]+\\.?[0-9]*"
static final String VARIABLE_REGEX = ":[a-zA-Z]+"
static final String COMMAND_REGEX = "[a-zA-Z_]+(\\?)?"
static final String OPEN_BRACKET_REGEX = "\\["
static final String CLOSE_BRACKET_REGEX = "\\]"
Package Functions
List< Command > parseScript (String script, Model model, VariableManager variableManager)
Private Member Functions
String removeComments (String script)
Private Attributes
CommandFactory myFactory
StringTokenizer myInstructions
VariableManager myVariableManager
Detailed Description
Parser for slogo. If given a string of commands, the parser will split it into tokens and convert them into a list of roots for runnable trees.
Author
Ethan Chang
Anna Miyajima
Definition at line 25 of file Parser.java.
Constructor & Destructor Documentation
backEnd.Parser.Parser (CommandFactory commandFactory)
Constructor for the parser
Definition at line 41 of file Parser.java.
Member Function Documentation
Command backEnd.Parser.makeTree (String commandName, Model model, VariableManager variableManager, Map< String, Command > commandsmap)
Creates commands from strings and inserts them as children of existing commands Recursive method, returns root of the tree
Parameters
commandName
Returns
Exceptions
RuntimeException
Definition at line 97 of file Parser.java.
References commands.templates.Command.addChild(), commands.CommandFactory.buildCommand(), backEnd.Model.getCommandsMap(), and commands.templates.Command.getNumChildrenNeeded().
Referenced by backEnd.Parser.parseScript().
List<Command> backEnd.Parser.parseScript (String script, Model model, VariableManager variableManager) package
Called by the model if the input script is valid. At this point, the parser will split the script up into different lines and individual commands. The Parser will then call the CommandFactory to build all of the commands and add them to the returned list
Parameters
script Raw input from the user (always error free)
Returns
A list of commands to be sent to the ScriptManager
Definition at line 56 of file Parser.java.
References backEnd.Model.getCommandsMap(), backEnd.Parser.makeTree(), backEnd.Parser.removeComments(), and commands.templates.Command.toString().
Referenced by backEnd.Model.runScript().
String backEnd.Parser.removeComments (String script) private
Definition at line 76 of file Parser.java.
Referenced by backEnd.Parser.parseScript().
Member Data Documentation
final String backEnd.Parser.CLOSE_BRACKET_REGEX = "\\]" static
Definition at line 31 of file Parser.java.
final String backEnd.Parser.COMMAND_REGEX = "[a-zA-Z_]+(\\?)?" static
Definition at line 29 of file Parser.java.
final String backEnd.Parser.CONSTANT_REGEX = "-?[0-9]+\\.?[0-9]*" static
Definition at line 27 of file Parser.java.
CommandFactory backEnd.Parser.myFactory private
Definition at line 33 of file Parser.java.
StringTokenizer backEnd.Parser.myInstructions private
Definition at line 34 of file Parser.java.
VariableManager backEnd.Parser.myVariableManager private
Definition at line 35 of file Parser.java.
final String backEnd.Parser.OPEN_BRACKET_REGEX = "\\[" static
Definition at line 30 of file Parser.java.
final String backEnd.Parser.VARIABLE_REGEX = ":[a-zA-Z]+" static
Definition at line 28 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/Parser.java