slogo_team06: titlePanes.TitlePaneFactory Class Reference
titlePanes.TitlePaneFactory Class Reference
Public Member Functions
TitlePaneFactory (double maxHeight)
TitledPane buildTitleFrame (String type, Controller contr) throws Exception
Collection< TitledPane > buildAllTitleFrames (Controller contr)
Package Functions
void implementTitlePane (String type, Class<?> panelClass)
Private Attributes
Map< String, Class<?> > implementedTitlePanes
double MAX_HEIGHT
Detailed Description
Definition at line 16 of file TitlePaneFactory.java.
Constructor & Destructor Documentation
titlePanes.TitlePaneFactory.TitlePaneFactory (double maxHeight)
Definition at line 21 of file TitlePaneFactory.java.
References titlePanes.TitlePaneFactory.implementTitlePane().
Member Function Documentation
Collection<TitledPane> titlePanes.TitlePaneFactory.buildAllTitleFrames (Controller contr)
Definition at line 50 of file TitlePaneFactory.java.
References titlePanes.TitlePaneFactory.buildTitleFrame().
TitledPane titlePanes.TitlePaneFactory.buildTitleFrame (String type, Controller contr) throws Exception
Definition at line 36 of file TitlePaneFactory.java.
Referenced by titlePanes.TitlePaneFactory.buildAllTitleFrames().
void titlePanes.TitlePaneFactory.implementTitlePane (String type, Class<?> panelClass) package
Definition at line 32 of file TitlePaneFactory.java.
Referenced by titlePanes.TitlePaneFactory.TitlePaneFactory().
Member Data Documentation
Map<String, Class<?> > titlePanes.TitlePaneFactory.implementedTitlePanes private
Definition at line 18 of file TitlePaneFactory.java.
double titlePanes.TitlePaneFactory.MAX_HEIGHT private
Definition at line 19 of file TitlePaneFactory.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/titlePanes/TitlePaneFactory.java