slogo_team06: titlePanes.DisplayTitlePane Class Reference
titlePanes.DisplayTitlePane Class Reference
Public Member Functions
DisplayTitlePane (Controller contr)
Private Member Functions
Node makeBackgroundColorBox (Controller contr)
Node makeGridLinesBox (Controller contr)
Node makeTurtleImageChooser (Controller contr)
void openFile (Controller contr)
Detailed Description
Definition at line 17 of file DisplayTitlePane.java.
Constructor & Destructor Documentation
titlePanes.DisplayTitlePane.DisplayTitlePane (Controller contr)
Definition at line 19 of file DisplayTitlePane.java.
References titlePanes.DisplayTitlePane.makeBackgroundColorBox(), titlePanes.DisplayTitlePane.makeGridLinesBox(), and titlePanes.DisplayTitlePane.makeTurtleImageChooser().
Member Function Documentation
Node titlePanes.DisplayTitlePane.makeBackgroundColorBox (Controller contr) private
Definition at line 29 of file DisplayTitlePane.java.
Referenced by titlePanes.DisplayTitlePane.DisplayTitlePane().
Node titlePanes.DisplayTitlePane.makeGridLinesBox (Controller contr) private
Definition at line 45 of file DisplayTitlePane.java.
References backEnd.Controller.toggleGridLines().
Referenced by titlePanes.DisplayTitlePane.DisplayTitlePane().
Node titlePanes.DisplayTitlePane.makeTurtleImageChooser (Controller contr) private
Definition at line 59 of file DisplayTitlePane.java.
References titlePanes.DisplayTitlePane.openFile().
Referenced by titlePanes.DisplayTitlePane.DisplayTitlePane().
void titlePanes.DisplayTitlePane.openFile (Controller contr) private
Definition at line 72 of file DisplayTitlePane.java.
References backEnd.Controller.changeTurtleImage().
Referenced by titlePanes.DisplayTitlePane.makeTurtleImageChooser().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/titlePanes/DisplayTitlePane.java