slogo_team06: main.MasterWindow Class Reference
main.MasterWindow Class Reference
Public Member Functions
void start (Stage primaryStage) throws Exception
Static Public Member Functions
static void main (String[] args)
Package Functions
void buildWorkspace ()
void saveWorkspacePreferences (File file)
void loadWorkspacePreferences (File file)
Private Member Functions
void tabChanged (Tab tab)
void setKeyListener ()
void setMouseListener ()
Private Attributes
Stage myStage
Scene myScene
Parser myParser
Workspace myCurrentWorkspace
CommandFactory myCommandFactory
Pane myRoot = new VBox()
TabPane myTabs = new TabPane()
MenuBar myMenuBar
Detailed Description
Definition at line 19 of file MasterWindow.java.
Member Function Documentation
void main.MasterWindow.buildWorkspace () package
Definition at line 48 of file MasterWindow.java.
References main.MasterWindow.setKeyListener(), main.MasterWindow.setMouseListener(), and main.MasterWindow.tabChanged().
Referenced by main.MasterMenuBar.buildNewWorkspaceMenuItem(), and main.MasterWindow.start().
void main.MasterWindow.loadWorkspacePreferences (File file) package
Definition at line 62 of file MasterWindow.java.
References frontEnd.Workspace.loadPropertiesFromFile().
Referenced by main.MasterMenuBar.loadWorkspacePreferences().
static void main.MasterWindow.main (String[] args) static
Definition at line 29 of file MasterWindow.java.
void main.MasterWindow.saveWorkspacePreferences (File file) package
Definition at line 59 of file MasterWindow.java.
References frontEnd.Workspace.savePropertiesToFile().
Referenced by main.MasterMenuBar.saveWorkspacePreferences().
void main.MasterWindow.setKeyListener () private
Definition at line 73 of file MasterWindow.java.
References frontEnd.Workspace.getKeyListener().
Referenced by main.MasterWindow.buildWorkspace(), and main.MasterWindow.tabChanged().
void main.MasterWindow.setMouseListener () private
Definition at line 76 of file MasterWindow.java.
References frontEnd.Workspace.getMouseListener().
Referenced by main.MasterWindow.buildWorkspace().
void main.MasterWindow.start (Stage primaryStage) throws Exception
Definition at line 34 of file MasterWindow.java.
References main.MasterWindow.buildWorkspace().
void main.MasterWindow.tabChanged (Tab tab) private
Definition at line 66 of file MasterWindow.java.
References main.MasterWindow.setKeyListener().
Referenced by main.MasterWindow.buildWorkspace().
Member Data Documentation
CommandFactory main.MasterWindow.myCommandFactory private
Definition at line 24 of file MasterWindow.java.
Workspace main.MasterWindow.myCurrentWorkspace private
Definition at line 23 of file MasterWindow.java.
MenuBar main.MasterWindow.myMenuBar private
Definition at line 27 of file MasterWindow.java.
Parser main.MasterWindow.myParser private
Definition at line 22 of file MasterWindow.java.
Pane main.MasterWindow.myRoot = new VBox() private
Definition at line 25 of file MasterWindow.java.
Scene main.MasterWindow.myScene private
Definition at line 21 of file MasterWindow.java.
Stage main.MasterWindow.myStage private
Definition at line 20 of file MasterWindow.java.
TabPane main.MasterWindow.myTabs = new TabPane() private
Definition at line 26 of file MasterWindow.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/main/MasterWindow.java