slogo_team06: titlePanes.VariableTitlePane Class Reference
titlePanes.VariableTitlePane Class Reference
Public Member Functions
VariableTitlePane (Controller contr) throws IOException
void updateVariables () throws IOException
Private Member Functions
void writeVariables (Set< Object > keys)
Private Attributes
VBox myRoot
Properties myVarProps
Map< String, String > myVarMap
Detailed Description
Definition at line 17 of file VariableTitlePane.java.
Constructor & Destructor Documentation
titlePanes.VariableTitlePane.VariableTitlePane (Controller contr) throws IOException
Definition at line 23 of file VariableTitlePane.java.
Member Function Documentation
void titlePanes.VariableTitlePane.updateVariables () throws IOException
Definition at line 34 of file VariableTitlePane.java.
References titlePanes.VariableTitlePane.writeVariables().
Referenced by panels.ParameterPanel.updateVariables().
void titlePanes.VariableTitlePane.writeVariables (Set< Object > keys) private
Definition at line 50 of file VariableTitlePane.java.
Referenced by titlePanes.VariableTitlePane.updateVariables().
Member Data Documentation
VBox titlePanes.VariableTitlePane.myRoot private
Definition at line 19 of file VariableTitlePane.java.
Map<String, String> titlePanes.VariableTitlePane.myVarMap private
Definition at line 21 of file VariableTitlePane.java.
Properties titlePanes.VariableTitlePane.myVarProps private
Definition at line 20 of file VariableTitlePane.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/titlePanes/VariableTitlePane.java