slogo_team06: backEnd.Model Class Reference
backEnd.Model Class Reference
Public Member Functions
Model (Parser parser)
void setupTurtleManager (View view)
void setTurtleObserver (View view)
TurtleManager getTurtleManager ()
Map< String, Command > getCommandsMap ()
DoubleProperty getBackgroundIndex ()
void setBackgroundIndex (double index)
void setPaletteArguments (int index, int red, int green, int blue)
StringProperty getPaletteArguments ()
void setVariableProperties (File f)
Static Public Attributes
static final int INITIAL_BACKGROUND_INDEX = 0
Package Functions
int runScript (String script)
Private Attributes
Parser myParser
Turtle myTurtle
VariableManager myVariableManager
TurtleManager myTurtleManager
HashMap< String, Command > myCommandsList
DoubleProperty myBackgroundIndex = new SimpleDoubleProperty()
StringProperty myPalette
Detailed Description
Model for SLogo. The model holds a turtle manager which holds the turtles for the workspace.
Author
Brian Bolze
Ethan Chang
Eli Lichtenberg
Anna Miyajima
Definition at line 30 of file Model.java.
Constructor & Destructor Documentation
backEnd.Model.Model (Parser parser)
Constructor for model. Initializes the variable manager, commandList, and the initial background index for the workspace
Parameters
parser Parser which can be used in the workspace
Definition at line 47 of file Model.java.
Member Function Documentation
DoubleProperty backEnd.Model.getBackgroundIndex ()
Returns the background index for the workspace
Returns
background index
Definition at line 124 of file Model.java.
References backEnd.Model.myBackgroundIndex.
Referenced by backEnd.Controller.Controller().
Map<String, Command> backEnd.Model.getCommandsMap ()
Return a map mapping string and commands
Returns
Definition at line 115 of file Model.java.
References backEnd.Model.myCommandsList.
Referenced by commands.CommandFactory.buildCommand(), backEnd.Parser.makeTree(), and backEnd.Parser.parseScript().
StringProperty backEnd.Model.getPaletteArguments ()
Definition at line 142 of file Model.java.
References backEnd.Model.myPalette.
Referenced by backEnd.Controller.Controller().
TurtleManager backEnd.Model.getTurtleManager ()
Returns the model's turtle manager
Returns
turtleManager
Definition at line 106 of file Model.java.
References backEnd.Model.myTurtleManager.
Referenced by commands.templates.TurtleCommand.getMyTurtleManager().
int backEnd.Model.runScript (String script) package
Called by the Controller when the Run button has been pressed by the user. Privacy level is Package because the Controller is in the backEnd package also
Parameters
script The input string of syntax from the text-field
Returns
Returns 0 if the input is valid. Returns 1 if there is a syntax error. Can be extended to return different Doubles for different types of syntax errors.
Definition at line 80 of file Model.java.
References backEnd.Parser.parseScript().
Referenced by backEnd.Controller.runScript().
void backEnd.Model.setBackgroundIndex (double index)
Set the index for the background
Parameters
index index for the background index
Definition at line 133 of file Model.java.
Referenced by commands.onechild.SetBackgroundCommand.execute().
void backEnd.Model.setPaletteArguments (int index, int red, int green, int blue)
Definition at line 137 of file Model.java.
Referenced by commands.SetPaletteCommand.execute().
void backEnd.Model.setTurtleObserver (View view)
Adds turtle observer to the view
Parameters
view view for the workspace
Definition at line 97 of file Model.java.
void backEnd.Model.setupTurtleManager (View view)
Sets up the turtleManager by adding an observer to it so it can be tracked by the front end
Parameters
view View for the workspace
Definition at line 61 of file Model.java.
References frontEnd.View.getCanvasHeight(), frontEnd.View.getCanvasWidth(), and backEnd.turtle.TurtleManager.updateActiveTurtleList().
Referenced by backEnd.Controller.Controller().
void backEnd.Model.setVariableProperties (File f)
Definition at line 146 of file Model.java.
References backEnd.VariableManager.setVarProperties().
Referenced by backEnd.Controller.setVariableProperties().
Member Data Documentation
final int backEnd.Model.INITIAL_BACKGROUND_INDEX = 0 static
Definition at line 32 of file Model.java.
DoubleProperty backEnd.Model.myBackgroundIndex = new SimpleDoubleProperty() private
Definition at line 38 of file Model.java.
Referenced by backEnd.Model.getBackgroundIndex().
HashMap<String, Command> backEnd.Model.myCommandsList private
Definition at line 37 of file Model.java.
Referenced by backEnd.Model.getCommandsMap().
StringProperty backEnd.Model.myPalette private
Definition at line 39 of file Model.java.
Referenced by backEnd.Model.getPaletteArguments().
Parser backEnd.Model.myParser private
Definition at line 33 of file Model.java.
Turtle backEnd.Model.myTurtle private
Definition at line 34 of file Model.java.
TurtleManager backEnd.Model.myTurtleManager private
Definition at line 36 of file Model.java.
Referenced by backEnd.Model.getTurtleManager().
VariableManager backEnd.Model.myVariableManager private
Definition at line 35 of file Model.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/backEnd/Model.java