slogo_team06: frontEnd.Workspace Class Reference
frontEnd.Workspace Class Reference
Public Member Functions
Workspace (Parser parser)
Workspace (Properties preferences, Parser parser)
EventHandler< KeyEvent > getKeyListener ()
EventHandler< MouseEvent > getMouseListener ()
void savePropertiesToFile (File file)
void loadPropertiesFromFile (File file)
Private Member Functions
void printProps ()
void loadDisplayProperties ()
void saveDisplayProperties ()
Private Attributes
Properties myDisplayProperties
Model myModel
View myView
Controller myController
double myWidth = 900
double myHeight = 600
Static Private Attributes
static final String BACKGROUND = "background"
static final Properties DEFAULT_DISPLAY_PROPERTIES = new Properties()
Detailed Description
Definition at line 20 of file Workspace.java.
Constructor & Destructor Documentation
frontEnd.Workspace.Workspace (Parser parser)
Definition at line 35 of file Workspace.java.
References frontEnd.Workspace.DEFAULT_DISPLAY_PROPERTIES.
frontEnd.Workspace.Workspace (Properties preferences, Parser parser)
Definition at line 39 of file Workspace.java.
Member Function Documentation
EventHandler<KeyEvent> frontEnd.Workspace.getKeyListener ()
Definition at line 54 of file Workspace.java.
References backEnd.Controller.myKeyListener.
Referenced by main.MasterWindow.setKeyListener().
EventHandler<MouseEvent> frontEnd.Workspace.getMouseListener ()
Definition at line 58 of file Workspace.java.
References backEnd.Controller.myMouseListener.
Referenced by main.MasterWindow.setMouseListener().
void frontEnd.Workspace.loadDisplayProperties () private
Definition at line 92 of file Workspace.java.
References frontEnd.View.changeBackgroundColor().
Referenced by frontEnd.Workspace.loadPropertiesFromFile().
void frontEnd.Workspace.loadPropertiesFromFile (File file)
Definition at line 74 of file Workspace.java.
References frontEnd.Workspace.loadDisplayProperties(), and frontEnd.Workspace.printProps().
Referenced by main.MasterWindow.loadWorkspacePreferences().
void frontEnd.Workspace.printProps () private
Definition at line 86 of file Workspace.java.
Referenced by frontEnd.Workspace.loadPropertiesFromFile().
void frontEnd.Workspace.saveDisplayProperties () private
Definition at line 98 of file Workspace.java.
References frontEnd.View.getBackgroundColor().
Referenced by frontEnd.Workspace.savePropertiesToFile().
void frontEnd.Workspace.savePropertiesToFile (File file)
Definition at line 62 of file Workspace.java.
References frontEnd.Workspace.saveDisplayProperties().
Referenced by main.MasterWindow.saveWorkspacePreferences().
Member Data Documentation
final String frontEnd.Workspace.BACKGROUND = "background" static private
Definition at line 22 of file Workspace.java.
final Properties frontEnd.Workspace.DEFAULT_DISPLAY_PROPERTIES = new Properties() static private
Definition at line 33 of file Workspace.java.
Referenced by frontEnd.Workspace.Workspace().
Controller frontEnd.Workspace.myController private
Definition at line 28 of file Workspace.java.
Properties frontEnd.Workspace.myDisplayProperties private
Definition at line 24 of file Workspace.java.
double frontEnd.Workspace.myHeight = 600 private
Definition at line 31 of file Workspace.java.
Model frontEnd.Workspace.myModel private
Definition at line 26 of file Workspace.java.
View frontEnd.Workspace.myView private
Definition at line 27 of file Workspace.java.
double frontEnd.Workspace.myWidth = 900 private
Definition at line 30 of file Workspace.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team06/repository/src/frontEnd/Workspace.java